(() => {
  "use strict";

  const levels = [
    {
      id: "b1-plus",
      code: "B1+",
      title: "Foundation and control",
      description: "Consolidate the structures and habits that make intermediate English accurate, useful and easy to understand.",
      outcome: "Handle everyday situations, explain experiences clearly and write connected paragraphs with reliable grammar.",
      modules: [
        { id: "b1-grammar", title: "Grammar control", focus: "Core tenses, modals, conditionals, articles and sentence building.", skills: ["grammar", "use-of-english"] },
        { id: "b1-vocabulary", title: "Everyday vocabulary", focus: "Collocations, word families, phrasal verbs and practical topic language.", skills: ["vocabulary", "english-thinking", "technical-english"] },
        { id: "b1-reading", title: "Reading for meaning", focus: "Short articles, messages and narratives with main-idea and detail strategies.", skills: ["reading", "critical-thinking"] },
        { id: "b1-communication", title: "Everyday communication", focus: "Descriptions, stories, requests and short opinion exchanges.", skills: ["speaking", "writing", "fluency", "english-thinking"] },
        { id: "b1-sound", title: "Clear English", focus: "Key vowel contrasts, word stress and intelligible connected speech.", skills: ["listening", "pronunciation"] }
      ],
      exam: "B1+ progress exam"
    },
    {
      id: "b2",
      code: "B2",
      title: "Functional and academic English",
      description: "Move from correct sentences to flexible choices in texts, discussions, study and work.",
      outcome: "Understand extended texts, defend an opinion, write organised B2 genres and interact with confidence.",
      modules: [
        { id: "b2-grammar", title: "Grammar in context", focus: "Mixed tenses, passive voice, clauses, modality and advanced linking.", skills: ["grammar", "use-of-english"] },
        { id: "b2-vocabulary", title: "Precision and collocation", focus: "Topic vocabulary, register, word formation and natural combinations.", skills: ["vocabulary"] },
        { id: "b2-reading", title: "Reading between the lines", focus: "Reports, articles, interviews and narratives with inference and tone.", skills: ["reading", "critical-thinking"] },
        { id: "b2-writing", title: "B2 writing studio", focus: "Essays, reports, reviews, proposals, narratives and formal emails.", skills: ["writing", "academic-english", "professional-english", "technical-english"] },
        { id: "b2-speaking", title: "Discussion and problem solving", focus: "Comparing, speculating, negotiating and responding to counterarguments.", skills: ["speaking", "fluency", "professional-english"] },
        { id: "b2-listening", title: "Natural-speed listening", focus: "Interviews, announcements, lectures and speaker attitude.", skills: ["listening", "pronunciation"] }
      ],
      exam: "B2 progress exam"
    },
    {
      id: "b2-plus",
      code: "B2+",
      title: "Range, nuance and fluency",
      description: "Stretch beyond safe language with complex ideas, precise vocabulary and faster decisions.",
      outcome: "Sustain longer arguments, infer unstated meaning and adapt register in demanding academic and professional contexts.",
      modules: [
        { id: "b2p-grammar", title: "Complex grammar choices", focus: "Inversion, emphasis, reduced clauses, ellipsis and nuanced modality.", skills: ["grammar", "use-of-english"] },
        { id: "b2p-language", title: "Advanced lexical control", focus: "Connotation, idioms, sophisticated collocations and word formation.", skills: ["vocabulary"] },
        { id: "b2p-reading", title: "Argument and evidence", focus: "Long-form journalism, science writing and competing viewpoints.", skills: ["reading", "critical-thinking"] },
        { id: "b2p-production", title: "Fluent production", focus: "Timed speaking, synthesis, summaries and controlled rewriting.", skills: ["speaking", "writing", "fluency", "academic-english"] },
        { id: "b2p-technical", title: "Technical English studio", focus: "Systems, requirements, processes, evidence, failure modes, safeguards and audience-aware technical explanation.", skills: ["technical-english", "professional-english", "academic-english"] },
        { id: "b2p-listening", title: "Connected speech lab", focus: "Reduced forms, discourse markers, stance and varied delivery.", skills: ["listening", "pronunciation"] }
      ],
      exam: "B2+ range and fluency exam"
    },
    {
      id: "c1",
      code: "C1",
      title: "Advanced, natural and flexible English",
      description: "Develop the control needed for complex academic, professional and intellectual communication.",
      outcome: "Read and evaluate complex ideas, write with a controlled register and speak spontaneously with nuance.",
      modules: [
        { id: "c1-grammar", title: "Advanced grammar and discourse", focus: "Clefts, fronting, advanced conditionals, hedging and discourse grammar.", skills: ["grammar", "use-of-english"] },
        { id: "c1-vocabulary", title: "Sophisticated expression", focus: "Nominalisation, metaphor, register, idiomatic precision and academic phraseology.", skills: ["vocabulary"] },
        { id: "c1-reading", title: "Critical and academic reading", focus: "Research-style texts, bias, assumptions, synthesis and authorial purpose.", skills: ["reading", "critical-thinking"] },
        { id: "c1-writing", title: "C1 writing and synthesis", focus: "Argumentative essays, critical responses, proposals and formal correspondence.", skills: ["writing", "academic-english", "professional-english"] },
        { id: "c1-speaking", title: "Academic and professional speaking", focus: "Presentations, negotiation, challenge, defence and spontaneous follow-up.", skills: ["speaking", "academic-english", "professional-english", "technical-english", "fluency"] },
        { id: "c1-listening", title: "Complex listening", focus: "Lectures, debates, implied meaning, attitude and multiple accents.", skills: ["listening", "pronunciation"] }
      ],
      exam: "C1 integrated exam"
    }
  ];

  const skills = [
    { id: "grammar", icon: "GR", title: "Grammar", description: "Understand form, meaning and register, then use grammar in real context.", color: "green" },
    { id: "vocabulary", icon: "VO", title: "Vocabulary", description: "Learn words through collocations, families, register, connotation and retrieval.", color: "gold" },
    { id: "reading", icon: "RE", title: "Reading", description: "Read for gist, detail, inference, tone, purpose and critical response.", color: "blue" },
    { id: "writing", icon: "WR", title: "Writing", description: "Plan, draft, self-review and refine texts from B1+ messages to C1 arguments.", color: "coral" },
    { id: "listening", icon: "LI", title: "Listening", description: "Build comprehension from clear speech to natural speed, reductions and attitude.", color: "purple" },
    { id: "speaking", icon: "SP", title: "Speaking", description: "Practise fluency, interaction, explanation, discussion and defending a position.", color: "teal" },
    { id: "pronunciation", icon: "PR", title: "Pronunciation", description: "Train sounds, stress, rhythm, linking, weak forms and intelligibility.", color: "rose" },
    { id: "use-of-english", icon: "UE", title: "Use of English", description: "Practise cloze, transformations, word formation, errors, collocations and phrasal verbs.", color: "gold" },
    { id: "critical-thinking", icon: "CT", title: "Critical thinking", description: "Infer, evaluate evidence, identify assumptions and formulate counterarguments.", color: "blue" },
    { id: "fluency", icon: "FL", title: "Fluency training", description: "Build speaking speed and flexibility through timed description, comparison, explanation and speculation.", color: "coral" },
    { id: "english-thinking", icon: "ET", title: "English thinking", description: "Paraphrase, define, describe and retrieve meaning without translating word by word.", color: "teal" },
    { id: "academic-english", icon: "AC", title: "Academic English", description: "Use evidence, cautious claims, structure and source-aware language in study contexts.", color: "purple" },
    { id: "professional-english", icon: "PR", title: "Professional English", description: "Handle meetings, emails, interviews, reports, presentations and workplace problem-solving.", color: "rose" },
    { id: "technical-english", icon: "TE", title: "Technical English", description: "Explain systems, processes, evidence, constraints, failure modes and safeguards precisely to specialist and non-specialist audiences.", color: "blue" }
  ];

  const activities = [
    { id: "vocab-education-collocation", skill: "vocabulary", level: "b1-plus", mode: "quiz", type: "choice", taskType: "Collocation choice", instruction: "Choose the natural collocation.", prompt: "Students are encouraged to ___ notes during the lecture.", options: ["make", "do", "take", "give"], answer: 2, explanation: "Take notes is the standard collocation.", topic: "skill-vocabulary" },
    { id: "vocab-technology-family", skill: "vocabulary", level: "b2", mode: "quiz", type: "choice", taskType: "Word family", instruction: "Choose the form that completes the sentence.", prompt: "The new system is highly ___ and can be adapted to different teams.", options: ["flexibility", "flexible", "flexibly", "flexibilise"], answer: 1, explanation: "The adjective flexible follows be and describes the system.", topic: "skill-vocabulary" },
    { id: "vocab-climate-register", skill: "vocabulary", level: "b2-plus", mode: "quiz", type: "choice", taskType: "Register and meaning", instruction: "Choose the most precise formal option.", prompt: "The report says the policy could ___ inequality if it is not revised.", options: ["make worse", "exacerbate", "do bad", "upset up"], answer: 1, explanation: "Exacerbate means make a problem more severe and is appropriate in formal analysis.", topic: "skill-vocabulary" },
    { id: "vocab-meaning-retrieval", skill: "vocabulary", level: "c1", mode: "challenge", title: "Explain without translating", prompt: "Explain the meaning of ‘substantial’ without using the word itself or translating it. Then give two natural collocations.", preparation: ["Think of quantity, importance and degree.", "Use a definition, an example and a contrast."], checklist: ["Clear definition", "Two collocations", "One contrast or limitation"], sample: "A substantial change is large or important enough to have a noticeable effect.", topic: "skill-vocabulary" },

    { id: "reading-urban-gardens", skill: "reading", level: "b1-plus", mode: "quiz", type: "choice", taskType: "Reading inference", instruction: "Read the text and choose the best inference.", passageTitle: "A garden above the street", passage: "When the residents converted the unused roof into a garden, they expected fresher herbs. They did not expect neighbours who had never spoken to begin sharing tools and advice. The harvest is modest, but the weekly gardening session has become the building’s most reliable meeting point.", prompt: "What unexpected benefit did the project create?", options: ["A large commercial harvest", "More interaction between residents", "A cheaper building", "A replacement for local shops"], answer: 1, explanation: "The text contrasts the modest harvest with the new social connection between neighbours.", topic: "skill-reading" },
    { id: "reading-science-purpose", skill: "reading", level: "b2", mode: "quiz", type: "choice", taskType: "Author purpose", instruction: "Read the text and identify the author’s main purpose.", passageTitle: "Small experiments, better decisions", passage: "A pilot project is not a promise that a solution will work everywhere. It is a controlled opportunity to observe, revise and decide what evidence is still missing. Treating a pilot as a public-relations success can hide useful failures; treating it as a learning process makes those failures informative.", prompt: "Why does the author contrast two ways of treating a pilot?", options: ["To argue that pilots should never be public", "To show why honest evaluation improves learning", "To prove every pilot fails", "To recommend replacing evidence with publicity"], answer: 1, explanation: "The contrast supports the argument that transparent evaluation turns failures into useful evidence.", topic: "skill-reading" },
    { id: "reading-c1-assumptions", skill: "reading", level: "c1", mode: "challenge", title: "Challenge an assumption", prompt: "Read a short opinion article of your choice. Identify one assumption the writer makes, decide whether it is justified and write a three-sentence response.", preparation: ["Underline the writer’s main claim.", "Ask what must be true for the claim to follow.", "Look for evidence, omissions and alternative explanations."], checklist: ["Claim identified", "Assumption stated", "Evidence evaluated", "Alternative considered"], sample: "The writer assumes that convenience is the main reason people adopt the service, but cost and social pressure could also explain the behaviour.", topic: "skill-reading" },

    { id: "writing-b1-email", skill: "writing", level: "b1-plus", mode: "challenge", title: "Informal email: change of plans", prompt: "Write 100–120 words to a friend explaining why you cannot attend a planned activity, suggesting an alternative and asking a follow-up question.", preparation: ["Open warmly and explain the change clearly.", "Use at least two linking expressions.", "Close with a natural question."], checklist: ["All three content points", "Informal register", "Paragraphing", "Accurate past and future forms"], sample: "Do not read the model until you have self-reviewed your own draft.", topic: "skill-writing" },
    { id: "writing-b2-report", skill: "writing", level: "b2", mode: "challenge", title: "Report: improve a study space", prompt: "Write a 180–220 word report for a college committee. Describe two problems with the current study space and recommend practical improvements.", preparation: ["Use headings or clear paragraphs.", "Support recommendations with reasons.", "Use a formal, objective register."], checklist: ["Purpose and audience clear", "Two problems", "Actionable recommendations", "Formal linking and vocabulary"], sample: "A strong report separates findings from recommendations and makes each proposal easy to act on.", topic: "skill-writing" },
    { id: "writing-c1-synthesis", skill: "writing", level: "c1", mode: "challenge", title: "Critical synthesis", prompt: "Write 250–280 words comparing two viewpoints on whether universities should record all lectures. Reach a qualified conclusion rather than simply choosing a side.", preparation: ["Represent both positions fairly.", "Use concession and contrast.", "State what your conclusion depends on."], checklist: ["Balanced synthesis", "Evidence or examples", "Nuanced thesis", "Controlled C1 register", "Self-review completed"], sample: "A qualified conclusion explains when a policy is useful and what safeguards or limits it needs.", topic: "skill-writing" },

    { id: "listening-b1-announcement", skill: "listening", level: "b1-plus", mode: "quiz", type: "choice", taskType: "Listening for detail", instruction: "Play the announcement, then choose the correct detail.", transcript: "Good morning. The 9:20 service to Northbridge will now leave from platform four, not platform two. Passengers should keep their tickets ready and allow extra time to cross the station.", prompt: "Where will the train leave from?", options: ["Platform two", "Platform four", "Northbridge station office", "The bus stop"], answer: 1, explanation: "The announcement corrects the original platform and says the service will leave from platform four.", topic: "skill-listening" },
    { id: "listening-b2-attitude", skill: "listening", level: "b2", mode: "quiz", type: "choice", taskType: "Speaker attitude", instruction: "Play or read the extract and identify the speaker’s attitude.", transcript: "The proposal is certainly ambitious. I would be more convinced, however, if the team explained how the timetable could be funded. At present, the figures leave too many questions unanswered.", prompt: "How does the speaker feel about the proposal?", options: ["Unreservedly enthusiastic", "Cautiously doubtful", "Angry about a personal insult", "Completely indifferent"], answer: 1, explanation: "Ambitious is positive, but the unanswered questions make the overall attitude cautious and doubtful.", topic: "skill-listening" },
    { id: "listening-c1-note-taking", skill: "listening", level: "c1", mode: "challenge", title: "Lecture notes and inference", prompt: "Listen to a two-minute academic explanation using SpeechSynthesis or a teacher’s recording. Produce five notes, one implied conclusion and one question for the speaker.", preparation: ["Write keywords, not full sentences.", "Mark examples separately from claims.", "Listen again only to confirm uncertain links."], checklist: ["Five useful notes", "Main claim", "Implied conclusion", "Follow-up question"], sample: "Your notes should allow another student to reconstruct the lecture’s argument without a full transcript.", topic: "skill-listening" },

    { id: "speaking-b1-description", skill: "speaking", level: "b1-plus", mode: "challenge", title: "Thirty-second description", prompt: "Speak for 30 seconds describing a place where you study. Mention what is there, what you usually do and one change you would make.", preparation: ["Use a simple beginning–detail–opinion structure.", "Include one present simple and one present continuous sentence."], checklist: ["30 seconds", "Specific details", "Clear sequence", "Understandable pronunciation"], sample: "Use the optional voice prompt below the activity to practise with a conversation partner.", topic: "skill-speaking" },
    { id: "speaking-b2-problem-solving", skill: "speaking", level: "b2", mode: "challenge", title: "Solve a community problem", prompt: "You and a partner have a limited budget to improve a neighbourhood. Discuss three options, compare them and agree on one plan.", preparation: ["Ask for your partner’s priorities.", "Use phrases for comparing, conceding and reaching agreement.", "Give at least one reason and one drawback for each option."], checklist: ["Interaction", "Comparison", "Reasons", "Agreement or justified disagreement"], sample: "I can see the benefit of X; nevertheless, Y would have a wider impact because…", topic: "skill-speaking" },
    { id: "speaking-c1-defence", skill: "speaking", level: "c1", mode: "challenge", title: "Defend a nuanced position", prompt: "Argue for or against the claim ‘Technology makes people less independent’. Present a qualified position, respond to a counterargument and finish with a condition.", preparation: ["Define what independent means in your argument.", "Distinguish convenience from dependence.", "Use one concession and one hypothetical example."], checklist: ["Clear position", "Counterargument", "Nuance", "Spontaneous follow-up"], sample: "The effect depends less on technology itself than on whether users retain the ability to act without it.", topic: "skill-speaking" },

    { id: "pronunciation-stress", skill: "pronunciation", level: "b1-plus", mode: "challenge", title: "Word-stress awareness", prompt: "Read aloud: PHOtograph, phoTOGraphy, photoGRAPHic. Mark the stressed syllable and record yourself saying the three forms.", preparation: ["Tap once on the strongest syllable.", "Keep unstressed vowels shorter and weaker.", "Compare the word family, not isolated words."], checklist: ["Stress moves correctly", "Vowels remain clear", "Three recordings"], sample: "Stress can move when a suffix changes the word family.", topic: "skill-pronunciation" },
    { id: "pronunciation-linking", skill: "pronunciation", level: "b2", mode: "challenge", title: "Linking and rhythm", prompt: "Shadow this sentence three times: ‘I’d like to ask you about the results of the experiment.’ Focus on linking consonants to vowels and keeping the content words prominent.", preparation: ["Listen to the browser model first.", "Underline the content words.", "Do not pronounce every word with equal force."], checklist: ["Smooth linking", "Natural rhythm", "Content-word stress", "Third attempt clearer than first"], sample: "Connected speech should remain intelligible; speed is less important than a stable rhythm.", topic: "skill-pronunciation" },
    { id: "pronunciation-c1-intonation", skill: "pronunciation", level: "c1", mode: "challenge", title: "Intonation and stance", prompt: "Say ‘That is an interesting proposal’ three ways: genuinely positive, politely doubtful and strongly ironic. Explain what changes in pitch, stress and context.", preparation: ["Keep the words constant.", "Change the focus word and pitch movement.", "Explain how a listener could misread the intention."], checklist: ["Three distinguishable versions", "Stance explained", "Context supplied"], sample: "Intonation carries attitude, but listeners interpret it together with context and word choice.", topic: "skill-pronunciation" },

    { id: "use-cloze-linker", skill: "use-of-english", level: "b1-plus", mode: "quiz", type: "choice", taskType: "Open cloze", instruction: "Choose the linker that creates the correct relationship.", prompt: "The route was longer than expected. ___, everyone arrived before the meeting began.", options: ["However", "Because", "Although", "Despite"], answer: 0, explanation: "However introduces a contrast with the previous sentence and can stand at the beginning of this sentence.", topic: "skill-use-of-english" },
    { id: "use-word-formation", skill: "use-of-english", level: "b2", mode: "quiz", type: "choice", taskType: "Word formation", instruction: "Choose the correct form of the word in brackets.", prompt: "The committee questioned the ___ of the timetable. (FEASIBLE)", options: ["feasibility", "feasible", "feasibly", "unfeasiblely"], answer: 0, explanation: "The noun feasibility names the quality being questioned.", topic: "skill-use-of-english" },
    { id: "use-transformation", skill: "use-of-english", level: "b2-plus", mode: "quiz", type: "choice", taskType: "Key-word transformation", instruction: "Choose the sentence with the same meaning.", prompt: "‘We only understood the risk after the test.’ Which option keeps the meaning?", options: ["Only after the test did we understand the risk.", "Only after the test we understood the risk.", "Only after the test had we understand the risk.", "Only after the test did understood we the risk."], answer: 0, explanation: "A negative or limiting fronted expression triggers subject–auxiliary inversion: did we understand.", topic: "skill-use-of-english" },
    { id: "use-c1-hedging", skill: "use-of-english", level: "c1", mode: "quiz", type: "choice", taskType: "Register and hedging", instruction: "Choose the most appropriately cautious academic sentence.", prompt: "The findings ___ suggest that the intervention improved retention.", options: ["definitely prove", "appear to", "are totally showing", "must absolutely mean"], answer: 1, explanation: "Appear to expresses a cautious interpretation suitable for academic writing.", topic: "skill-use-of-english" }
  ];

  const projects = [
    { id: "project-b1-story", level: "b1-plus", title: "My English story", description: "Create a two-minute personal story and a 150-word written version using clear sequence markers.", skills: ["speaking", "writing", "grammar"] },
    { id: "project-b1-guide", level: "b1-plus", title: "Everyday survival guide", description: "Design a practical guide for a visitor with vocabulary, instructions and a short audio explanation.", skills: ["vocabulary", "writing", "speaking"] },
    { id: "project-b2-report", level: "b2", title: "Evidence-based campus report", description: "Read two short sources, compare their claims and submit a formal report with recommendations.", skills: ["reading", "writing", "critical-thinking"] },
    { id: "project-b2-podcast", level: "b2", title: "Mini podcast", description: "Plan and record a four-minute episode explaining a current issue with an introduction, evidence and conclusion.", skills: ["listening", "speaking", "vocabulary"] },
    { id: "project-b2p-debate", level: "b2-plus", title: "Structured debate", description: "Research both sides of a question, anticipate objections and defend a qualified position.", skills: ["critical-thinking", "speaking", "use-of-english"] },
    { id: "project-b2p-rewrite", level: "b2-plus", title: "Register transformation", description: "Rewrite an informal message as a professional email and explain every major language choice.", skills: ["writing", "vocabulary", "grammar"] },
    { id: "project-c1-synthesis", level: "c1", title: "Academic synthesis", description: "Combine two contrasting texts into a balanced critical response with an explicit line of reasoning.", skills: ["reading", "writing", "critical-thinking"] },
    { id: "project-c1-presentation", level: "c1", title: "Professional presentation", description: "Deliver a seven-minute presentation, answer hostile follow-up questions and submit a reflective review.", skills: ["speaking", "listening", "pronunciation"] }
  ];

  const diagnostic = [
    { id: "diag-1", level: "b1-plus", skill: "grammar", type: "choice", prompt: "I ___ here since 2022.", options: ["work", "am working", "have worked", "worked"], answer: 2, explanation: "Since gives a starting point connected to now, so present perfect is appropriate." },
    { id: "diag-2", level: "b1-plus", skill: "vocabulary", type: "choice", prompt: "Please ___ attention to the final instruction.", options: ["do", "make", "pay", "put"], answer: 2, explanation: "Pay attention is the standard collocation." },
    { id: "diag-3", level: "b2", skill: "grammar", type: "choice", prompt: "By the time we arrived, the lecture ___.", options: ["started", "has started", "had started", "was starting"], answer: 2, explanation: "Past perfect places the earlier event before another past reference." },
    { id: "diag-4", level: "b2", skill: "reading", type: "choice", prompt: "If an author gives evidence for a claim, what should you check next?", options: ["Whether the evidence actually supports it", "Whether every sentence is short", "Whether the title is attractive", "Whether you agree immediately"], answer: 0, explanation: "Critical reading tests the relationship between evidence and claim." },
    { id: "diag-5", level: "b2-plus", skill: "use-of-english", type: "choice", prompt: "Rarely ___ such a rapid change in public opinion.", options: ["we have seen", "have we seen", "we saw have", "did we have saw"], answer: 1, explanation: "Fronted negative adverbs such as rarely trigger inversion." },
    { id: "diag-6", level: "c1", skill: "writing", type: "choice", prompt: "Which opening is most suitable for a formal proposal?", options: ["Hey, here is my idea", "This proposal outlines three measures designed to…", "You guys should really…", "I wanna talk about…"], answer: 1, explanation: "The second option states purpose and uses a formal register." }
  ];

  const quizActivity = (id, skill, level, taskType, prompt, options, answer, explanation) => ({ id, skill, level, mode: "quiz", type: "choice", taskType, instruction: "Choose the option that best fits the context.", prompt, options, answer, explanation, topic: `skill-${skill}` });
  const challengeActivity = (id, skill, level, title, prompt, preparation, checklist, sample) => ({ id, skill, level, mode: "challenge", title, prompt, preparation, checklist, sample, topic: `skill-${skill}` });

  activities.push(
    quizActivity("vocab-work-collocation", "vocabulary", "b1-plus", "Collocation", "Before the interview, try to ___ a good impression.", ["do", "make", "take", "put"], 1, "Make a good impression is the natural collocation."),
    quizActivity("vocab-travel-phrasal", "vocabulary", "b1-plus", "Phrasal verb", "We had to ___ the meeting until everyone could attend.", ["put off", "put up", "put out", "put through"], 0, "Put off means postpone."),
    quizActivity("vocab-environment-family", "vocabulary", "b2", "Word family", "The city has introduced measures to reduce air ___. (POLLUTE)", ["polluting", "pollution", "polluted", "pollutanting"], 1, "Pollution is the noun required after air."),
    quizActivity("vocab-science-register", "vocabulary", "b2", "Formal register", "The results provide ___ evidence that the method is reliable.", ["convincing", "cool", "okay-ish", "nice"], 0, "Convincing is precise and appropriate for a formal research context."),
    quizActivity("vocab-finance-collocation", "vocabulary", "b2-plus", "Finance collocation", "The company needs to ___ costs without reducing quality.", ["cut", "slice", "scratch", "break"], 0, "Cut costs is the established business collocation."),
    quizActivity("vocab-ai-connotation", "vocabulary", "b2-plus", "Connotation", "Calling the system ‘experimental’ rather than ‘unreliable’ presents a more ___ evaluation.", ["neutral", "careless", "hostile", "impossible"], 0, "Neutral avoids the strongly negative connotation of unreliable."),
    quizActivity("vocab-c1-idiom", "vocabulary", "c1", "Fixed expression", "The researcher refused to ___ conclusions before the full data set was available.", ["jump to", "leap in", "run at", "fall over"], 0, "Jump to conclusions means decide too quickly without sufficient evidence."),
    challengeActivity("vocab-collocation-map", "vocabulary", "b2", "Build a collocation map", "Choose one academic or professional word and create five useful combinations: adjective + noun, verb + noun, noun + preposition, adverb + adjective and one negative or contrasting combination.", ["Start with a word you have recently met.", "Check whether each combination sounds natural in a sentence.", "Say the five sentences aloud."], ["Five combinations", "Five original sentences", "Register checked", "One contrast"], "For demand: meet demand, growing demand, demand for skills, sharply increased demand, weak demand."),

    quizActivity("reading-travel-detail", "reading", "b1-plus", "Reading detail", "A guide says: ‘The museum is free on the first Sunday, but visitors must reserve a timed ticket.’ What must visitors do on that day?", ["Pay at the entrance", "Reserve a timed ticket", "Visit on Saturday", "Bring a guidebook"], 1, "The sentence explicitly requires a timed reservation even though entry is free."),
    quizActivity("reading-interview-tone", "reading", "b2", "Tone", "An interviewee says, ‘I value the flexibility of remote work, although I miss the quick decisions that happen when colleagues share a room.’ What is the tone?", ["Balanced", "Completely negative", "Sarcastic", "Uncertain about having a job"], 0, "The speaker recognises an advantage and a disadvantage, creating a balanced tone."),
    quizActivity("reading-science-evidence", "reading", "b2", "Evidence", "A science article reports that a study found a relationship between sleep and memory but warns that the sample was small. What should a careful reader do?", ["Treat the result as a useful indication, not final proof", "Ignore the study completely", "Assume every person behaves identically", "Remove the warning from the summary"], 0, "The limitation does not erase the finding, but it reduces how confidently it can be generalised."),
    quizActivity("reading-professional-purpose", "reading", "b2-plus", "Professional purpose", "A company memo lists three recurring delays, assigns an owner to each and sets review dates. What is its main purpose?", ["Entertain staff", "Turn problems into an action plan", "Advertise a product", "Describe a personal memory"], 1, "Owners and review dates turn the problems into a plan for action."),
    quizActivity("reading-academic-inference", "reading", "c1", "Academic inference", "An essay notes that a policy was popular in surveys but rarely used in practice. What question should the reader ask?", ["Why reported approval did not become behaviour", "Whether surveys are always illegal", "Why popularity proves effectiveness", "Whether practice is irrelevant"], 0, "The contrast invites an investigation of the gap between stated attitudes and behaviour."),
    challengeActivity("reading-bias-audit", "critical-thinking", "b2-plus", "Audit a reading for bias", "Choose a news or opinion text and identify its claim, selected evidence, omitted perspective and one word that reveals an attitude.", ["Separate what the text states from what it assumes.", "Find one plausible alternative interpretation.", "Write a neutral two-sentence summary."], ["Claim", "Evidence", "Omission", "Loaded language", "Neutral summary"], "A bias audit does not require rejecting a text; it requires making its choices visible."),

    challengeActivity("writing-b1-description", "writing", "b1-plus", "Describe a meaningful place", "Write 100–120 words describing a place that matters to you. Include sensory detail, one routine and one change you would make.", ["Use a clear opening sentence.", "Move from general location to specific details.", "Finish with a personal reason."], ["100–120 words", "Sensory vocabulary", "Present simple accuracy", "Clear paragraph shape"], "A strong description helps the reader picture the place instead of listing disconnected objects."),
    challengeActivity("writing-b2-opinion", "writing", "b2", "Opinion essay", "Write 180–220 words answering: ‘Should schools teach practical financial skills as a compulsory subject?’ Present both sides before your conclusion.", ["Define what practical skills include.", "Use one example for each side.", "Make your conclusion conditional or qualified."], ["Balanced argument", "Cohesive paragraphs", "Examples", "Clear conclusion", "Register checked"], "A good opinion essay develops reasons rather than repeating the same view in different words."),
    challengeActivity("writing-b2-email", "professional-english", "b2", "Formal email", "Write 160–190 words to a service manager reporting a problem with a booking, explaining its impact and requesting a reasonable remedy.", ["State the purpose in the opening.", "Use a calm, factual tone.", "Make a specific request and provide contact details."], ["Formal opening", "Accurate details", "Specific remedy", "Polite closing"], "Formal complaints are strongest when the requested action is clear and proportionate."),
    challengeActivity("writing-b2p-proposal", "professional-english", "b2-plus", "Workplace proposal", "Write 220–260 words proposing one change that could improve communication in a team. Explain costs, benefits, risks and how success could be measured.", ["Use headings or a clear report structure.", "Distinguish evidence from prediction.", "Include a practical implementation step."], ["Purpose", "Benefits and risks", "Measure of success", "Professional register", "Recommendation"], "A proposal becomes persuasive when the reader can see how the idea would be tested and adjusted."),
    challengeActivity("writing-c1-critical-response", "academic-english", "c1", "Critical response", "Write 260–300 words responding to a claim that artificial intelligence will make traditional study unnecessary. Evaluate the claim rather than simply agreeing or disagreeing.", ["Define the key terms.", "Distinguish access to information from learning.", "Use cautious academic language and a qualified conclusion."], ["Precise thesis", "Counterargument", "Evidence or example", "Hedging", "C1 cohesion"], "A critical response makes the reasoning visible and acknowledges what would change the conclusion."),

    quizActivity("listening-dialogue-intention", "listening", "b1-plus", "Listening intention", "A colleague says, ‘I can send the file now, unless you still need to add the final chart.’ What is the colleague doing?", ["Offering a choice", "Cancelling the project", "Complaining about the chart", "Giving a past report"], 0, "The speaker offers to send the file while checking whether an addition is still needed."),
    quizActivity("listening-interview-detail", "listening", "b2", "Listening detail", "An interviewee says, ‘The course was demanding, but the weekly feedback helped me change my approach before the final assignment.’ What helped the speaker improve?", ["A shorter course", "Weekly feedback", "A new teacher", "Fewer assignments"], 1, "The speaker directly identifies weekly feedback as the useful support."),
    quizActivity("listening-lecture-inference", "listening", "b2-plus", "Lecture inference", "A lecturer says, ‘The graph looks impressive; however, the categories were changed halfway through the project.’ What is the warning?", ["The graph may not support a fair comparison", "The graph is too small to see", "The project was cancelled", "The categories are irrelevant"], 0, "Changing categories can make comparisons misleading even when the graph looks persuasive."),
    quizActivity("listening-news-attitude", "listening", "c1", "News attitude", "A reporter says, ‘Officials describe the outcome as a success, though residents are still waiting for the promised repairs.’ What attitude is signalled?", ["Uncritical celebration", "Sceptical distance", "Personal amusement", "Complete confusion"], 1, "Though introduces evidence that makes the official positive description less convincing."),
    challengeActivity("listening-note-taking", "listening", "b2", "Note-taking ladder", "Listen to a two-minute explanation using SpeechSynthesis or a teacher recording. Take notes in three columns: claim, evidence and implication.", ["Listen once for the overall structure.", "Listen again for examples and qualifications.", "Write one sentence explaining the speaker’s conclusion."], ["Three columns", "Five useful notes", "One implication", "Conclusion"], "Good notes preserve relationships between ideas, not just isolated words."),
    challengeActivity("listening-accent-awareness", "listening", "c1", "Accent and attitude", "Listen to two versions of the same short message spoken at different speeds or with different voices. Record which words carry the attitude and what remains intelligible.", ["Focus on stressed words first.", "Use the transcript only after a first attempt.", "Separate unfamiliar accent features from unfamiliar vocabulary."], ["Main message", "Attitude", "Key stressed words", "Uncertainty explained"], "Effective listeners use redundancy, context and stressed content words to maintain meaning."),

    challengeActivity("speaking-b1-story", "speaking", "b1-plus", "Personal story", "Tell a one-minute story about a time a plan changed. Use a clear beginning, problem, response and result.", ["Use past simple for the main events.", "Use past continuous for background.", "Finish with what you learned."], ["One minute", "Four story stages", "Time markers", "Clear ending"], "A story is easier to follow when each event answers what happened next and why it mattered."),
    challengeActivity("speaking-b2-job-interview", "professional-english", "b2", "Job interview simulation", "Answer: ‘Tell me about a time you solved a difficult problem.’ Give context, action, result and a reflection on what you would do differently.", ["Prepare four keywords, not a script.", "Use one specific example.", "End by connecting the skill to the role."], ["Context", "Action", "Result", "Reflection", "Natural delivery"], "A structured example sounds more credible than a list of general strengths."),
    challengeActivity("speaking-b2p-meeting", "professional-english", "b2-plus", "Lead a meeting", "Open a five-minute meeting, invite two viewpoints, summarise agreement and assign a next step. The topic is improving a shared digital workflow.", ["Set the purpose and time.", "Use polite interruption and turn-taking language.", "Summarise decisions precisely."], ["Agenda", "Interaction", "Neutral facilitation", "Decision", "Next step"], "Professional fluency includes making other people’s contributions easier to understand."),
    challengeActivity("speaking-c1-university", "academic-english", "c1", "University interview", "Explain a project you would like to research. Clarify the question, method, limitation and expected contribution, then answer two follow-up questions.", ["Avoid unexplained specialist terms.", "Distinguish what you know from what you predict.", "Respond to a challenge without abandoning nuance."], ["Research question", "Method", "Limitation", "Contribution", "Follow-up"], "Academic speaking is persuasive when the speaker is precise about uncertainty."),
    challengeActivity("speaking-debate", "speaking", "c1", "Formal debate", "Defend the motion ‘Public transport should be free in major cities’. Present a case, answer a counterargument and propose one safeguard.", ["Define free: no fare, subsidised or income-based?", "Use evidence or a realistic example.", "Concede one legitimate concern."], ["Definition", "Case", "Counterargument", "Safeguard", "Closing statement"], "A strong debate response changes the level of the question instead of repeating a slogan."),

    quizActivity("pronunciation-vowels", "pronunciation", "b1-plus", "Minimal pair", "Which word has the vowel sound needed in ‘ship’ rather than ‘sheep’?", ["leave", "live", "bead", "seat"], 1, "Live has the short vowel in ship; leave, bead and seat have the long vowel in sheep."),
    quizActivity("pronunciation-stress-choice", "pronunciation", "b2", "Word stress", "Which syllable is normally stressed in ‘photography’?", ["PHO-to-graph-y", "pho-TOG-ra-phy", "pho-to-GRA-phy", "pho-to-graph-Y"], 1, "Photography normally stresses the second syllable: pho-TOG-ra-phy."),
    challengeActivity("pronunciation-shadowing", "pronunciation", "b1-plus", "Shadow a dialogue", "Play a short English dialogue, then repeat one speaker half a second behind the model. Focus on rhythm rather than perfect speed.", ["Choose 20–30 seconds.", "Mark stressed words.", "Record a first and final attempt."], ["Timing", "Rhythm", "Key words audible", "Improvement noted"], "Shadowing trains prediction, rhythm and connected speech together."),
    challengeActivity("pronunciation-weak-forms", "pronunciation", "b2-plus", "Weak forms", "Read: ‘I could have told you, but I thought you already knew.’ Reduce unstressed function words while keeping the content words prominent.", ["Underline could, have, you, but, I, you.", "Keep thought, already and knew prominent.", "Record a natural and an over-careful version."], ["Function-word reduction", "Content stress", "Contrast explained", "Intelligibility"], "Weak forms make a sentence easier to process when the main information remains prominent."),
    challengeActivity("pronunciation-c1-professional-stance", "pronunciation", "c1", "Professional stance", "Say ‘We could revisit that assumption’ as supportive, cautious and firmly corrective. Explain how pitch and focus change the relationship.", ["Keep the wording constant.", "Move the focus to different words.", "Describe the listener’s likely interpretation."], ["Three stances", "Focus shift", "Pitch movement", "Listener effect"], "Advanced pronunciation includes managing interpersonal meaning, not just individual sounds."),

    quizActivity("use-open-cloze-preposition", "use-of-english", "b1-plus", "Open cloze", "The workshop is divided ___ three short sessions.", ["in", "into", "on", "at"], 1, "Divided into introduces the resulting parts."),
    quizActivity("use-phrasal-verb", "use-of-english", "b2", "Phrasal verb", "The team had to ___ the figures before publishing the report.", ["go over", "go under", "go out", "go against"], 0, "Go over means examine or check carefully."),
    quizActivity("use-error-correction", "use-of-english", "b2", "Error correction", "Choose the corrected sentence: ‘Despite of the delay, the event began.’", ["Despite the delay, the event began.", "Despite of the delay, the event began.", "Despite the delay, but the event began.", "Although of the delay, the event began."], 0, "Despite is followed directly by a noun phrase; despite of is not standard here."),
    quizActivity("use-transformation-causative", "use-of-english", "b2-plus", "Transformation", "Choose the closest meaning to ‘A technician repaired my laptop.’", ["I had my laptop repaired.", "I had repaired my laptop technician.", "My laptop had repairing.", "I made my laptop repair."], 0, "Have something done describes arranging for another person to perform the service."),
    quizActivity("use-idiom", "use-of-english", "b2-plus", "Idiomatic expression", "The new evidence means we need to ___ the drawing board.", ["return to", "return at", "go back on", "turn into"], 0, "Return to the drawing board means start planning again after a problem."),
    quizActivity("use-c1-nominalisation", "use-of-english", "c1", "Nominalisation", "The committee will decide whether to fund the project. Choose the nominalised version.", ["The committee’s decision on project funding is pending.", "The committee deciding funding is pendingly.", "The project fund decides the committee.", "The committee has decide to funding."], 0, "Decision and funding create a concise formal noun phrase."),

    quizActivity("critical-fact-opinion", "critical-thinking", "b1-plus", "Fact or opinion", "Which sentence is an opinion rather than a checkable fact?", ["The library opens at eight.", "The library is the most welcoming place on campus.", "The library has three floors.", "The library introduced a booking system."], 1, "Most welcoming expresses a personal evaluation rather than a directly measurable fact."),
    quizActivity("critical-evidence", "critical-thinking", "b2", "Evaluate evidence", "A product review uses only the company’s own claims. What is the main limitation?", ["The source may not be independent", "The product cannot exist", "Reviews never use evidence", "The claims must be false"], 0, "A company source can be informative but may have a commercial interest."),
    quizActivity("critical-assumption", "critical-thinking", "b2-plus", "Identify assumption", "A proposal says ‘Everyone will attend online because the recordings are available.’ What assumption is being made?", ["Access and recordings guarantee participation", "Online tools never fail", "Everyone dislikes meetings", "Recordings are illegal"], 0, "The proposal assumes that availability will lead people to attend or engage."),
    challengeActivity("critical-counterargument", "critical-thinking", "b2-plus", "Build a counterargument", "Take a claim you agree with and write the strongest reasonable objection. Then revise your original claim so it survives that objection.", ["State the claim fairly.", "Use a genuine concern, not a weak caricature.", "Qualify the revised claim."], ["Original claim", "Strong objection", "Evidence or example", "Revised claim"], "A stronger argument often becomes more precise after it acknowledges where it does not apply."),
    challengeActivity("critical-source-synthesis", "critical-thinking", "c1", "Synthesize perspectives", "Compare two sources that disagree about a policy. Identify one point of agreement, one genuine disagreement and one question neither source answers.", ["Summarise each source neutrally.", "Separate evidence from interpretation.", "Write a conclusion that preserves the uncertainty."], ["Two fair summaries", "Agreement", "Disagreement", "Open question", "Qualified conclusion"], "Synthesis is more than listing sources; it explains how their ideas relate."),

    challengeActivity("fluency-30-seconds", "fluency", "b1-plus", "30-second challenge", "Speak for 30 seconds describing your morning without stopping to translate. If you pause, paraphrase and continue.", ["Use five sequence markers.", "Do not restart a sentence.", "Record a second attempt."], ["30 seconds", "Sequence", "Paraphrase", "Second attempt"], "Fluency grows when communication continues even while vocabulary is still being retrieved."),
    challengeActivity("fluency-60-seconds", "fluency", "b2", "60-second comparison", "Compare studying alone and studying with others for one minute. Give two similarities, two differences and a preference.", ["Use comparison language.", "Keep a clear structure.", "Add one condition to your preference."], ["One minute", "Four comparisons", "Preference", "Condition"], "A timed structure reduces planning overload and makes range easier to measure."),
    challengeActivity("fluency-speculate", "fluency", "b2-plus", "Speculate under pressure", "Look at an unfamiliar image and speak for two minutes: describe, infer what happened before, predict what happens next and justify one guess.", ["Separate observation from inference.", "Use might, must and could.", "Keep the narrative moving."], ["Description", "Past inference", "Future prediction", "Justification"], "Speculation becomes clearer when the speaker labels certainty instead of presenting guesses as facts."),
    challengeActivity("fluency-c1-summary", "fluency", "c1", "Two-minute synthesis", "Listen to or read a short article and explain its main claim, strongest evidence, limitation and your own response in two minutes.", ["Take five keywords.", "Use signposting.", "Avoid retelling every detail."], ["Main claim", "Evidence", "Limitation", "Response", "Two minutes"], "Advanced fluency depends on selecting and organising information, not speaking without structure."),

    challengeActivity("thinking-circumlocution", "english-thinking", "b1-plus", "Circumlocution", "Describe a familiar object without naming it. Your partner or voice coach should guess it from your function, appearance and context.", ["Start with category.", "Explain what it is used for.", "Add one contrast."], ["Category", "Function", "Appearance", "Contrast"], "Circumlocution keeps communication moving when a precise word is unavailable."),
    challengeActivity("thinking-paraphrase", "english-thinking", "b2", "Paraphrase challenge", "Rewrite five short sentences using different vocabulary and grammar while keeping the meaning unchanged.", ["Underline the core meaning first.", "Change the structure, not just one word.", "Check that the register stays appropriate."], ["Five sentences", "Meaning preserved", "Structure changed", "Register checked"], "A paraphrase is successful when the new sentence is natural as well as accurate."),
    challengeActivity("thinking-definition", "english-thinking", "b2-plus", "Definition without translation", "Choose three abstract words and define them using a category, a characteristic, an example and a non-example.", ["Avoid the target word.", "Use a concrete example.", "Add a boundary or non-example."], ["Three definitions", "No translation", "Example", "Boundary"], "Precise definitions explain where a word applies and where it does not."),
    challengeActivity("thinking-c1-register", "english-thinking", "c1", "Think through register", "Take a casual sentence and reformulate it for a friend, a manager and an academic audience. Explain what changed and why.", ["Keep the propositional meaning.", "Change stance and degree of directness.", "Identify one lexical and one grammatical shift."], ["Three versions", "Meaning preserved", "Register explained", "Grammar shift"], "Register is a choice about relationship, purpose and expectations, not only a list of formal words."),

    challengeActivity("academic-abstract", "academic-english", "b2", "Academic abstract", "Write a 120-word abstract for a small study on how students use digital notes. Include aim, method, main result and limitation.", ["Use concise noun phrases.", "Avoid unsupported claims.", "Use cautious result language."], ["Aim", "Method", "Result", "Limitation", "120 words"], "An abstract lets a reader understand the research design and value quickly."),
    challengeActivity("academic-presentation", "academic-english", "b2-plus", "Mini presentation", "Give a three-minute presentation explaining one surprising finding from a source. Signpost the structure and answer one question.", ["Open with the question.", "Define specialist vocabulary.", "End by returning to the significance."], ["Signposting", "Evidence", "Explanation", "Question", "Conclusion"], "Academic presentation is a guided journey from question to evidence to significance."),
    challengeActivity("academic-c1-source", "academic-english", "c1", "Source-aware paragraph", "Write one paragraph that combines two sources without copying them. Use reporting verbs, a contrast and a qualified synthesis sentence.", ["Attribute each idea.", "Paraphrase before combining.", "Make your own relationship between sources explicit."], ["Two attributions", "Paraphrase", "Contrast", "Synthesis"], "Source-aware writing shows both where ideas come from and what you conclude from them."),
    challengeActivity("professional-meeting", "professional-english", "b1-plus", "Workplace update", "Give a 45-second update to a colleague about a task: progress, current problem, next action and time needed.", ["Use a clear order.", "Give a realistic time estimate.", "Ask whether support is needed."], ["Progress", "Problem", "Next action", "Time estimate"], "A useful update helps another person decide what to do next."),
    challengeActivity("professional-negotiation", "professional-english", "c1", "Business negotiation", "Negotiate a project deadline with a partner who wants speed and a partner who wants more testing. Reach an agreement with a review point.", ["Clarify interests, not just positions.", "Offer two possible compromises.", "State what happens if the condition is not met."], ["Interests", "Options", "Trade-off", "Agreement", "Review point"], "Professional negotiation protects relationships while making constraints and consequences explicit.")
  );

  activities.push(
    quizActivity("vocab-c1-nominalisation", "vocabulary", "c1", "Academic vocabulary", "The article questions the long-term ___ of the policy. (SUSTAIN)", ["sustainable", "sustainability", "sustainably", "sustainer"], 1, "Sustainability is the noun naming the quality being questioned."),
    quizActivity("reading-c1-tone", "reading", "c1", "Authorial tone", "A review calls a reform ‘a bold experiment whose early success should not be mistaken for proof’. What tone is created?", ["Carefully optimistic", "Uncritically celebratory", "Personally insulting", "Entirely comic"], 0, "Bold experiment is positive, but the warning limits the confidence of the praise."),
    quizActivity("listening-c1-inference", "listening", "c1", "Implied meaning", "A speaker says, ‘The figures are technically accurate; whether they answer the question we asked is another matter.’ What is implied?", ["Accuracy alone does not make evidence relevant", "The figures are fabricated", "The question has no answer", "Technical language is forbidden"], 0, "The speaker distinguishes correct data from data that addresses the intended question."),
    quizActivity("pronunciation-c1-linking", "pronunciation", "c1", "Connected speech", "Which strategy usually makes ‘next year’ sound more natural in connected speech?", ["Link the final consonant to the following vowel where appropriate", "Stress every syllable equally", "Pause between every word", "Delete the main verb"], 0, "Linking can connect neighbouring sounds while preserving the words and intelligibility."),
    quizActivity("use-c1-idiom", "use-of-english", "c1", "Idiomatic nuance", "The report does not ___ the possibility that the data was affected by seasonal factors.", ["rule out", "rule in", "rule over", "rule across"], 0, "Rule out means exclude a possibility; the sentence says it remains possible."),
    quizActivity("critical-c1-bias", "critical-thinking", "c1", "Bias and framing", "A report describes supporters as ‘concerned citizens’ but opponents as ‘a noisy minority’. What should a reader notice?", ["Uneven labels may frame the groups differently", "The report is automatically accurate", "The minority cannot have evidence", "Adjectives never influence interpretation"], 0, "The contrasting labels carry different connotations and may influence how readers evaluate each group."),
    quizActivity("academic-c1-register", "academic-english", "c1", "Academic register", "Choose the most cautious sentence for a research discussion.", ["The results prove the method works everywhere.", "The results may indicate that the method is effective in comparable settings.", "The results are totally awesome.", "The results obviously show everything."], 1, "May indicate and comparable settings hedge the claim and limit its scope appropriately.")
  );

  const lessonStages = [
    ["Understand the system", "Build a clear mental model before memorising forms. Start by identifying the communicative purpose and the context."],
    ["Notice it in context", "Read and listen for the target language in a short realistic situation. Mark the clues that make the choice natural."],
    ["Control the form", "Complete guided practice, check the explanation and record the pattern in your own example."],
    ["Use it independently", "Produce a short spoken or written response, then self-review for meaning, accuracy, range and register."],
    ["Stretch the choice", "Apply the skill to a B2, B2+ or C1 task where more than one form may be possible but the viewpoint changes."]
  ];
  levels.forEach((level) => level.modules.forEach((module, moduleIndex) => {
    module.lessons = lessonStages.map(([title, body], lessonIndex) => ({
      id: `${module.id}-lesson-${lessonIndex + 1}`,
      title: `${title}: ${module.title}`,
      body: `${body} This lesson focuses on ${module.focus.toLowerCase()}`,
      stage: lessonIndex < 2 ? "Input" : lessonIndex < 4 ? "Guided practice" : "Challenge"
    }));
    module.assessment = {
      quiz: `${module.title} checkpoint`,
      reading: `${level.code} reading connected to ${module.title.toLowerCase()}`,
      listening: `${level.code} listening task with a detail and inference question`,
      writing: `${level.code} written production linked to ${module.title.toLowerCase()}`,
      speaking: `${level.code} speaking follow-up linked to ${module.title.toLowerCase()}`,
      final: moduleIndex === level.modules.length - 1
    };
  }));

  const levelExams = levels.map((level) => ({
    id: `${level.id}-exam`,
    level: level.id,
    title: level.exam,
    questions: activities.filter((activity) => activity.level === level.id && activity.mode === "quiz"),
    production: activities.filter((activity) => activity.level === level.id && activity.mode === "challenge").slice(0, 4)
  }));

  window.EnglishUniversityData = { levels, skills, activities, projects, diagnostic, levelExams };
})();
