(() => {
  const makeTopic = (id, number, icon, title, subtitle, description, lesson, intro, questions, contrasts, mistakes, voicePrompt) => ({ id, number, icon, title, subtitle, description, lesson, partial: 1, guide: { intro, questions, contrasts, mistakes, voicePrompt } });

  const topics = [
    makeTopic("present-tenses", "01", "PR", "Present Tenses", "Simple, continuous and perfect forms", "Choose among present simple, present continuous, present perfect and present perfect continuous from meaning and time reference.", [
      ["Present simple", "Use it for routines, repeated events, permanent situations, facts and state verbs.", "She works from home twice a week."],
      ["Present continuous", "Use it for actions happening now, temporary situations and developing changes.", "She’s working from the library this week."],
      ["Present perfect", "Use it for past experience, completed results and unfinished time connected to now.", "She has finished three reports today."],
      ["Present perfect continuous", "Use it to emphasise duration, repeated activity or visible evidence of recent activity.", "She has been working since eight."]
    ], ["Present forms are chosen by viewpoint, not only by time. Ask whether the speaker presents a habit, an action in progress, a result connected to now or the duration of an activity.", "State verbs such as know, believe, own and understand normally prefer simple forms. Dynamic meanings of some verbs can still be continuous."], ["Is it a routine, fact or state?", "Is it happening now or temporary?", "Is there a present result or unfinished time period?", "Is duration or repeated activity the focus?"], [["I read every evening.", "A routine."], ["I’m reading now.", "An action in progress."], ["I’ve read the report.", "A completed present result."], ["I’ve been reading for two hours.", "Duration and activity are central."]], ["Do not use present perfect with a finished past time such as yesterday.", "Do not normally use continuous forms with state verbs."], "You are my B2 speaking coach. Practise present simple, present continuous, present perfect and present perfect continuous through an interview about routines, current projects, life experience and recent activity. Ask one question at a time, require full answers, identify the time signal and correct the tense with a short explanation. Include since, for, already, yet, now and at the moment. Speak only in English."),
    makeTopic("past-tenses", "02", "PA", "Past Tenses", "Simple, continuous and perfect forms", "Build a clear past timeline with completed events, background actions, earlier events and duration before a past point.", [
      ["Past simple", "Use it for completed events in finished past time and the main sequence of a story.", "We arrived at six."],
      ["Past continuous", "Use it for background or an action in progress around a past time.", "We were driving when it started to snow."],
      ["Past perfect", "Use it for an event completed before another past reference point.", "The train had left before we reached the station."],
      ["Past perfect continuous", "Use it for duration or repeated activity leading up to a past point.", "They had been waiting for an hour when the bus arrived."]
    ], ["Past tenses organise events on a timeline. Past simple moves the story forward; past continuous creates the scene; past perfect looks further back; past perfect continuous explains an earlier ongoing cause or duration.", "Past perfect needs a meaningful later past reference. It is not simply a more formal past simple."], ["Which action is the main completed event?", "What was already in progress?", "Which event happened earlier?", "Does earlier duration explain a later result?"], [["I cooked when she arrived.", "The cooking can be understood as a complete event after or around her arrival."], ["I was cooking when she arrived.", "Her arrival interrupts or occurs during the cooking."], ["I had cooked before she arrived.", "The cooking was complete first."], ["I had been cooking for an hour when she arrived.", "Earlier duration is emphasised."]], ["Do not use past perfect for every old event; use it to clarify earlier past time.", "Use while naturally with a longer background action and when with the shorter event."], "You are my B2 speaking coach. Tell an interrupted story and ask me to continue it using past simple, past continuous, past perfect and past perfect continuous. Make me identify background, main event, earlier event and earlier duration. Correct my timeline and ask me to repeat each corrected sentence. Include while, when, before, after and by the time. Speak only in English."),
    makeTopic("passive-voice", "03", "PV", "Passive Voice", "Six essential passive forms", "Form passive sentences with the correct tense of be plus a past participle and choose when the agent should be omitted.", [
      ["Present simple passive", "am/is/are + past participle for regular processes and facts.", "The rooms are cleaned daily."],
      ["Present continuous passive", "am/is/are being + past participle for a process happening now.", "The bridge is being repaired."],
      ["Present perfect passive", "has/have been + past participle for a present result.", "The results have been published."],
      ["Past simple passive", "was/were + past participle for a completed past event.", "The package was delivered yesterday."],
      ["Past continuous passive", "was/were being + past participle for a process in progress in the past.", "The road was being widened."],
      ["Past perfect passive", "had been + past participle for a passive event before another past event.", "The door had been locked before we arrived."]
    ], ["The passive changes focus: the receiver of the action becomes the grammatical subject. Keep the original tense by changing be, then add the past participle.", "Use by + agent only when the agent is important, surprising or necessary. Unknown or obvious agents are normally omitted."], ["What receives the action?", "Which tense does the meaning require?", "What form of be carries that tense?", "Is the agent useful enough to mention?"], [["Researchers test the sample.", "Active: focus on the researchers."], ["The sample is tested.", "Passive: focus on the sample or process."], ["They are testing the sample.", "Present continuous active."], ["The sample is being tested.", "Present continuous passive."]], ["Do not forget been in perfect passives or being in continuous passives.", "Only transitive verbs with an object can normally become passive."], "You are my B2 speaking coach. Practise present and past passive forms in a news report, factory tour and investigation. Give me active sentences to transform and passive contexts to identify. Make me preserve the original tense, choose the correct form of be and decide whether the agent matters. Correct missing been, being and irregular participles. Speak only in English."),
    makeTopic("active-passive", "04", "A/P", "Active vs Passive Voice", "Choose the most useful focus", "Decide whether the doer or receiver deserves sentence focus, then build the appropriate active or passive structure.", [
      ["Choose active", "Prefer active voice when the agent is known, important and responsible for the action.", "The committee approved the proposal."],
      ["Choose passive", "Prefer passive voice when the receiver, process or result is more important.", "The proposal was approved yesterday."],
      ["Mentioning the agent", "Add by + agent only when it contributes useful information.", "The novel was written by Toni Morrison."]
    ], ["Active and passive sentences can describe the same event but organise information differently. Good writers choose the version that connects naturally to the previous sentence.", "Passive voice is common in reports, scientific processes and news when the action or result matters more than the agent."], ["What information is already the topic?", "Is the agent known and important?", "Would omitting the agent make the sentence clearer?", "Does the chosen voice preserve the tense?"], [["A technician repaired the server.", "Use active when the technician’s responsibility matters."], ["The server was repaired overnight.", "Use passive when the restored server is the focus."]], ["Passive is not automatically more formal or better.", "Do not add by someone/people when the agent gives no useful information."], "You are my B2 speaking coach. Give me workplace, scientific and news situations. Ask me to choose active or passive voice, explain which participant deserves focus and say a full sentence in the correct tense. Challenge unnecessary by-agents and unclear passive sentences. Speak only in English."),
    makeTopic("mixed-tenses", "05", "MT", "Mixed Tenses", "Present and past forms in one context", "Use time relationships, aspect and discourse focus to choose among present and past simple, continuous and perfect forms.", [
      ["Find the reference point", "Locate now, a finished past time or another past event before choosing a tense.", "I have worked here since May, but I worked in Leeds last year."],
      ["Choose simple or continuous", "Simple often presents facts/results; continuous often presents activity, duration or temporary background.", "She has written five emails; she has been writing all morning."],
      ["Choose present or past", "Present perfect connects to now; past simple belongs to finished past time.", "I’ve seen him today; I saw him yesterday."],
      ["Order past events", "Use past perfect when the earlier event needs clarification.", "When I arrived, the meeting had started."]
    ], ["Mixed-tense questions are solved by reading the entire context. One marker may not be enough; combine the time phrase, whether the period is finished and whether the speaker focuses on result or activity.", "Draw a quick timeline when two or more events compete."], ["What is the reference time?", "Is the time period finished?", "Is the action complete, repeated or in progress?", "Is one past event earlier than another?"], [["I’ve lived here for five years.", "The situation continues now."], ["I lived there for five years.", "The period is finished."], ["She has painted the room.", "The result is visible."], ["She has been painting the room.", "The activity or its evidence is central."]], ["Do not choose from one keyword without reading the sentence.", "A grammatically possible tense may still be a poor contextual choice."], "You are my B2 speaking coach. Run a mixed-tense oral test using present and past simple, continuous, perfect and perfect continuous forms. Give me contexts with competing options and ask why one is best. Require a timeline explanation, correct the exact contrast and revisit my mistakes later. Speak only in English."),
    makeTopic("narrative-tenses", "06", "NT", "Narrative Tenses", "Background, events and flashbacks", "Tell coherent stories by separating background, main events, earlier causes and ongoing earlier activity.", [
      ["Set the scene", "Past continuous describes background actions and conditions.", "Rain was falling and people were hurrying home."],
      ["Move the story", "Past simple reports the main sequence of completed events.", "A taxi stopped and a woman stepped out."],
      ["Look back", "Past perfect reports an event completed before the story’s reference point.", "She had left her phone at the office."],
      ["Explain duration", "Past perfect continuous shows earlier ongoing activity or cause.", "She had been working for twelve hours."]
    ], ["Narrative tenses guide the reader’s attention. Background is like the stage; past-simple events are the actors’ movements; perfect forms provide flashbacks and causes.", "Once the earlier sequence is clear, writers often return to past simple rather than repeat past perfect unnecessarily."], ["What is background?", "Which event advances the story?", "What happened before the current scene?", "What earlier activity explains a condition?"], [["The alarm rang while I was sleeping.", "Short event plus background action."], ["I was tired because I had been travelling all night.", "A past condition explained by earlier duration."]], ["Do not keep every verb in past continuous; stories need completed events.", "Use past perfect strategically, not in every sentence of a flashback."], "You are my B2 speaking coach. Build a mystery story with me. Ask me to set the scene, narrate main events, add a flashback and explain an earlier ongoing cause using narrative tenses. Stop after each stage, correct my tense choice and ask me to retell the corrected part. Speak only in English."),
    makeTopic("time-expressions", "07", "TE", "Time Expressions", "Markers that locate and connect events", "Use since, for, already, yet, just, recently and past-time markers with compatible tense meanings.", [
      ["since and for", "Since introduces a starting point; for introduces a duration.", "since Monday · for three days"],
      ["already, yet and just", "These commonly connect recent events or expected results to the present.", "I’ve just arrived. Have you finished yet?"],
      ["now, at the moment, currently", "These often mark a current or temporary situation.", "I’m currently working on a new project."],
      ["finished past markers", "Yesterday, ago and last... normally place an event in finished past time.", "We met two years ago."],
      ["sequence markers", "While, when, before, after and by the time organise relationships between events.", "By the time I arrived, they had left."]
    ], ["Time expressions are clues, not mechanical commands. Their meaning must agree with the tense and with whether the time period is finished or still connected to now.", "Since can also introduce a clause; for gives the length of time."], ["Is it a point or duration?", "Is the time period finished?", "Does the marker show current activity, recent result or event sequence?", "Which event happened first?"], [["I’ve worked here since 2022.", "Starting point."], ["I’ve worked here for four years.", "Duration."], ["I saw her yesterday.", "Finished past time."], ["I’ve seen her recently.", "Recent time connected to now."]], ["Do not use ago with present perfect.", "Yet is common in questions and negatives; already is common in affirmatives."], "You are my B2 speaking coach. Quiz me orally on since, for, already, yet, just, recently, now, at the moment, currently, yesterday, ago, last, while, when, before, after and by the time. Give a meaning first and make me choose a marker and tense. Correct both parts and ask me to repeat the full sentence. Speak only in English."),
    makeTopic("choosing-tense", "08", "CT", "Choosing the Correct Tense", "A complete tense-selection method", "Compare simple/continuous, perfect/perfect continuous, present/past and active/passive choices systematically.", [
      ["Simple vs continuous", "Choose fact, habit or complete result versus activity, duration or temporary background.", "I write reports. · I’m writing one now."],
      ["Perfect vs perfect continuous", "Choose result/quantity versus activity/duration/evidence.", "I’ve written four pages. · I’ve been writing for an hour."],
      ["Present vs past", "Choose connection to now versus a finished past reference.", "I’ve met her before. · I met her last week."],
      ["Active vs passive", "Choose whether the agent or receiver/process should be the sentence focus.", "They repaired it. · It was repaired."]
    ], ["Tense selection is a decision process. Start with time, then aspect, then voice. This prevents an attractive keyword from making the decision alone.", "When two answers seem possible, ask what difference in viewpoint each would communicate."], ["What is the reference time?", "Is the focus fact/result or activity/duration?", "Does the event connect to now?", "Should the agent or receiver be the subject?"], [["She worked all morning.", "A finished past period."], ["She has been working all morning.", "The morning is viewed as continuing or relevant now."], ["Someone has changed the schedule.", "Agent/action focus."], ["The schedule has been changed.", "Result/receiver focus."]], ["Do not solve the voice question before identifying the tense.", "Do not assume continuous means longer; viewpoint matters."], "You are my B2 speaking coach. Give me difficult pairs that contrast simple and continuous, perfect and perfect continuous, present and past, and active and passive. Make me state the reference time, aspect and focus before answering. Accept alternatives only when I can explain the meaning difference. Speak only in English."),
    makeTopic("b2-cloze", "09", "B2", "B2 Story / Cloze Practice", "Mixed grammar in connected texts", "Apply mixed tenses, passive voice and narrative grammar across complete B2-level stories and reports.", [
      ["Read for overall meaning", "Understand the situation and timeline before focusing on individual gaps.", "Who is speaking, when, and why?"],
      ["Track reference points", "Mark now, finished past events, earlier past events and ongoing background.", "arrival → discovery → earlier cause"],
      ["Check local grammar", "After choosing the meaning, verify auxiliaries, participles, agreement and voice.", "had been waiting · was discovered"]
    ], ["Cloze work tests grammar beyond one sentence. A later line can reveal whether an earlier gap needs a present connection, a flashback or a passive focus.", "Read the complete paragraph once, solve the clearest gaps, then reread for consistency."], ["What is the text’s main reference time?", "Which events are background, main sequence or earlier causes?", "Is the agent important?", "Which marker controls the gap?"], [["When the door opened, everyone stopped talking.", "Main past event interrupts background."], ["The documents had been removed before the inspector arrived.", "Earlier passive event."], ["Researchers have recently discovered a pattern.", "Recent present result."], ["They have been studying it for months.", "Ongoing present duration."]], ["Do not solve gaps independently; maintain one coherent timeline.", "Check whether a passive participle needs been or being."], "You are my B2 speaking coach. Read me a short story or report with oral gaps. Mix present and past tenses, narrative forms and passive voice. Let me answer each gap, but periodically ask me to summarise the whole timeline and explain the focus. Correct grammar and coherence, then ask me to retell the text. Speak only in English.")
  ];

  const guides = Object.fromEntries(topics.map((topic) => [topic.id, topic.guide]));
  guides["present-tenses"].diagram = "present-system";
  guides["past-tenses"].diagram = "past-system";
  guides["passive-voice"].diagram = "passive-system";
  guides["choosing-tense"].diagram = "tense-choice";
  topics.forEach((topic) => delete topic.guide);
  const c = (topic, prompt, options, answer, explanation, taskType = "Mixed tense choice") => ({ topic, type: "choice", instruction: "Choose the form that best fits the complete context.", prompt, options, answer, explanation, taskType });
  const t = (topic, prompt, answers, explanation, taskType = "Open cloze") => ({ topic, type: "text", instruction: "Write the correct form or expression.", prompt, answers, explanation, taskType });
  const r = (topic, title, passage, prompt, options, answer, explanation, taskType = "Context cloze") => ({ ...c(topic, prompt, options, answer, explanation, taskType), passageTitle: title, passage });
  const rt = (topic, title, passage, prompt, answers, explanation, taskType = "Reading open cloze") => ({ ...t(topic, prompt, answers, explanation, taskType), passageTitle: title, passage });

  const banks = {
    "present-tenses": [
      c("present-tenses", "Marta usually ___ from home on Fridays.", ["works", "is working", "has worked", "has been working"], 0, "Usually marks a repeated routine, so present simple is the best choice."),
      c("present-tenses", "Please be quiet. I ___ to understand these figures.", ["try", "am trying", "have tried yesterday", "have been try"], 1, "The effort is happening now, so present continuous fits."),
      c("present-tenses", "I ___ three client calls so far today.", ["make", "am making", "have made", "have been making three"], 2, "So far today is unfinished time and three calls focuses on completed quantity."),
      c("present-tenses", "Her hands are covered in paint because she ___ the kitchen.", ["paints", "is painting every day", "has painted three kitchens", "has been painting"], 3, "Visible present evidence points to recent activity, so present perfect continuous fits."),
      c("present-tenses", "I ___ the answer, but I need time to explain it.", ["know", "am knowing", "have been knowing", "knowing"], 0, "Know is a state verb and normally takes a simple form."),
      c("present-tenses", "This month, we ___ a temporary office near the station.", ["use always", "are using", "have used in 2020", "uses"], 1, "This month and temporary context support present continuous."),
      c("present-tenses", "She ___ that novel twice.", ["reads now", "is reading twice", "has read", "has been read"], 2, "Twice gives completed quantity with present relevance."),
      c("present-tenses", "They ___ for a solution since Monday.", ["look", "are looking since", "have looked yesterday", "have been looking"], 3, "Since Monday gives an ongoing activity from a starting point to now."),
      t("present-tenses", "Complete: ‘We ___ the report yet.’ (not / finish)", ["have not finished", "haven't finished", "havent finished"], "Yet in a negative sentence commonly combines with present perfect."),
      t("present-tenses", "Correct the state verb: ‘I am believing your explanation.’", ["i believe your explanation", "i believe your explanation."], "Believe normally describes a state, so use present simple."),
      r("present-tenses", "A changing workplace", "Nora normally manages the front desk, but this week she is training two new assistants. She has completed the safety module, and she has been showing them the booking system since Monday.", "Which form focuses on Nora’s completed result?", ["normally manages", "is training", "has completed", "has been showing"], 2, "Has completed presents the finished safety module as a current result."),
      rt("present-tenses", "A changing workplace", "Nora normally manages the front desk, but this week she is training two new assistants. She has completed the safety module, and she has been showing them the booking system since Monday.", "Complete the ongoing activity: ‘She ___ them the system since Monday.’", ["has been showing", "she has been showing", "she's been showing", "shes been showing"], "The activity began on Monday and continues to the present."),
    ],
    "past-tenses": [
      c("past-tenses", "We ___ the contract yesterday afternoon.", ["signed", "were signing when", "had signed tomorrow", "have signed yesterday"], 0, "Yesterday afternoon is finished past time, so past simple fits."),
      c("past-tenses", "I ___ home when I saw the accident.", ["drove completely", "was driving", "had driven after", "have driven"], 1, "The driving was background in progress when the shorter event happened."),
      c("past-tenses", "By the time we arrived, the film ___.", ["started", "was starting now", "had started", "has started"], 2, "The film started before the later past arrival."),
      c("past-tenses", "He was exhausted because he ___ all night.", ["worked tomorrow", "was working after he slept", "had worked one task", "had been working"], 3, "Earlier duration explains his later past condition."),
      c("past-tenses", "While the guests ___, the lights suddenly went out.", ["danced", "were dancing", "had danced after", "have danced"], 1, "While introduces the longer background action."),
      c("past-tenses", "She opened the parcel and ___ the note inside.", ["read", "was reading before opening", "had read later", "has read"], 0, "Past simple moves the completed sequence forward."),
      c("past-tenses", "I recognised the street because I ___ there before.", ["lived tomorrow", "was living now", "had lived", "have lived yesterday"], 2, "The earlier experience occurred before the past recognition."),
      c("past-tenses", "They ___ for forty minutes when the doctor finally arrived.", ["waited next", "were waiting after", "had waited tomorrow", "had been waiting"], 3, "For forty minutes before a later past event calls for past perfect continuous."),
      t("past-tenses", "Complete: ‘The phone rang while I ___.’ (sleep)", ["was sleeping", "i was sleeping"], "The sleeping was already in progress when the phone rang."),
      t("past-tenses", "Correct the order: ‘When I got there, she already left.’", ["when i got there, she had already left", "she had already left", "when i got there she had already left"], "Past perfect clarifies that leaving happened before arrival."),
      r("past-tenses", "The missed interview", "Dylan had been travelling for three hours when his train stopped. He called the company, but the interviewer had already left by the time he reached the office.", "Which form emphasises Dylan’s earlier travel duration?", ["stopped", "called", "had been travelling", "had left"], 2, "Had been travelling focuses on duration leading up to the train stopping."),
      rt("past-tenses", "The missed interview", "Dylan had been travelling for three hours when his train stopped. He called the company, but the interviewer had already left by the time he reached the office.", "Complete the earlier event: ‘The interviewer ___ before Dylan arrived.’", ["had left", "had already left", "the interviewer had left"], "The interviewer’s departure occurred before Dylan’s arrival."),
    ],
    "passive-voice": [
      c("passive-voice", "Coffee ___ in more than seventy countries.", ["grows actively", "is grown", "is being grow", "has grew"], 1, "Present simple passive describes a general production fact."),
      c("passive-voice", "The main entrance ___ at the moment.", ["repairs", "is repairing itself", "is being repaired", "has been repair"], 2, "At the moment requires present continuous; passive focus gives is being repaired."),
      c("passive-voice", "The final results ___ already ___.", ["have / published", "have been / published", "are being / publish", "were / publishing"], 1, "Present perfect passive is have been + past participle."),
      c("passive-voice", "The sculpture ___ in 1894.", ["created", "was created", "was being create", "had been creating"], 1, "A completed event at a finished past date uses past simple passive."),
      c("passive-voice", "The road ___ when the storm began.", ["was being widened", "was widening itself", "had widened tomorrow", "has been widened yesterday"], 0, "The passive process was in progress when the storm began."),
      c("passive-voice", "The files ___ before the investigation started.", ["deleted", "were deleting", "had been deleted", "have been deleted yesterday"], 2, "Past perfect passive marks deletion before the later past investigation."),
      c("passive-voice", "Which sentence correctly omits an unknown agent?", ["Someone was stolen my wallet.", "My wallet was stolen.", "My wallet stole.", "Was stolen someone my wallet."], 1, "The receiver becomes subject; the unknown agent is unnecessary."),
      c("passive-voice", "Choose the present perfect passive question.", ["Have the invitations sent?", "Have the invitations been sent?", "Are the invitations been sent?", "Were sent the invitations?"], 1, "Question order is have + subject + been + past participle."),
      t("passive-voice", "Change to passive: ‘They clean the laboratory every evening.’", ["the laboratory is cleaned every evening", "the laboratory is cleaned every evening."], "Present simple active becomes am/is/are + past participle."),
      t("passive-voice", "Change to passive: ‘They were interviewing the witnesses.’", ["the witnesses were being interviewed", "the witnesses were being interviewed."], "Past continuous passive uses were being + past participle."),
      r("passive-voice", "A museum update", "The west gallery is being renovated this month. Several paintings have been moved, and a temporary exhibition was opened last Saturday. The safety system had been tested before visitors entered.", "Which form describes a process happening now?", ["have been moved", "was opened", "is being renovated", "had been tested"], 2, "Is being renovated is present continuous passive."),
      rt("passive-voice", "A museum update", "The west gallery is being renovated this month. Several paintings have been moved, and a temporary exhibition was opened last Saturday. The safety system had been tested before visitors entered.", "Complete: ‘The safety system ___ before visitors entered.’", ["had been tested"], "Past perfect passive expresses the earlier completed safety test."),
    ],
    "active-passive": [
      c("active-passive", "The report focuses on the discovery, not the scientists. Choose the best sentence.", ["Scientists discovered a new species.", "A new species was discovered.", "A new species discovered scientists.", "Scientists were discover."], 1, "Passive voice places the discovery in subject position and omits an unnecessary agent."),
      c("active-passive", "Responsibility matters. Which sentence gives the clearest focus?", ["The error was made.", "The accountant made the error.", "The error made the accountant.", "There was made an error."], 1, "Active voice clearly names the responsible agent."),
      c("active-passive", "The process is happening now. Choose the passive version of ‘Engineers are testing the system.’", ["The system tests engineers.", "The system is tested now.", "The system is being tested.", "The system has been testing."], 2, "Present continuous passive preserves are testing as is being tested."),
      c("active-passive", "Which by-agent is genuinely informative?", ["English is spoken by people.", "The window was broken by someone.", "The novel was written by Kazuo Ishiguro.", "The road is used by users."], 2, "The author’s identity is meaningful; the other agents are obvious or vague."),
      c("active-passive", "Choose the active sentence.", ["The samples were analysed overnight.", "The laboratory analysed the samples overnight.", "The samples had been analysed.", "The samples are being analysed."], 1, "The laboratory is the grammatical agent performing the action."),
      c("active-passive", "Choose the best formal process description.", ["We mix the solution and then we heat it.", "The solution is mixed and then heated.", "The solution mixes us.", "It is mix and heat."], 1, "Passive voice keeps the process and material as the topic."),
      c("active-passive", "The previous sentence is about the damaged bridge. Which continuation is most cohesive?", ["Workers repaired the bridge overnight.", "The bridge was repaired overnight.", "Someone did repairs to it by workers.", "It repaired workers."], 1, "Passive voice keeps the bridge as the sentence topic."),
      c("active-passive", "Which sentence should remain active because the agent is central?", ["The suspect was arrested at dawn.", "Marie Curie discovered radium with Pierre Curie.", "The forms are checked daily.", "The building was completed in 2010."], 1, "The named discoverers are important information."),
      t("active-passive", "Rewrite with receiver focus: ‘Someone has changed the password.’", ["the password has been changed", "the password has been changed."], "Present perfect passive focuses on the current result."),
      t("active-passive", "Rewrite actively: ‘The decision was announced by the director.’", ["the director announced the decision", "the director announced the decision."], "The by-agent becomes the active subject."),
      r("active-passive", "A data incident", "A monitoring system detected unusual activity at midnight. The security team closed the affected account, and all users were informed before morning. A full review is being conducted.", "Why is ‘all users were informed’ passive?", ["The users performed the action.", "The focus is on the affected users, not the informer.", "Passive always describes midnight.", "The agent must be named."], 1, "The receivers and outcome are more relevant than who sent the message."),
      rt("active-passive", "A data incident", "A monitoring system detected unusual activity at midnight. The security team closed the affected account, and all users were informed before morning. A full review is being conducted.", "Make this active: ‘A full review is being conducted by the security team.’", ["the security team is conducting a full review", "the security team is conducting a full review."], "The named agent becomes subject while present continuous is preserved."),
    ],
    "mixed-tenses": [
      c("mixed-tenses", "I ___ this company in 2021, and I ___ here ever since.", ["joined / have worked", "have joined / worked", "was joining / work", "had joined / am work"], 0, "In 2021 is finished past; ever since connects the continuing situation to now."),
      c("mixed-tenses", "She ___ dinner when she realised she ___ the oven on.", ["cooked / left", "was cooking / had left", "has cooked / leaves", "had cooked / was leaving"], 1, "Cooking was background; leaving the oven on happened earlier."),
      c("mixed-tenses", "We ___ three solutions so far, but none of them works.", ["test", "are testing three", "have tested", "had tested yesterday"], 2, "So far marks unfinished time and three focuses on completed attempts."),
      c("mixed-tenses", "He looks tired because he ___ all morning.", ["worked last year", "is working every day", "has been studying", "had studied before yesterday"], 2, "Present evidence and ongoing duration support present perfect continuous."),
      c("mixed-tenses", "While I ___ the figures, my manager ___ me an urgent message.", ["checked / was sending", "was checking / sent", "had checked / sends", "have checked / sent"], 1, "The checking was background; the message was the completed event."),
      c("mixed-tenses", "I can’t open the file because it ___.", ["was deleted in 2019", "has been deleted", "is deleting", "had been deleting"], 1, "Present perfect passive explains the current result."),
      c("mixed-tenses", "By the time the police arrived, the witnesses ___ for twenty minutes.", ["wait", "were waiting now", "had been waiting", "have waited"], 2, "Duration before a past reference calls for past perfect continuous."),
      c("mixed-tenses", "This week the team ___ remotely, although it normally ___ in the office.", ["works / is working", "is working / works", "has worked yesterday / works", "worked / is working every day"], 1, "Temporary current arrangement contrasts with routine."),
      c("mixed-tenses", "The hall ___ right now, so the meeting is in Room 4.", ["paints", "is painting", "is being painted", "has painted"], 2, "A current passive process uses is being painted."),
      c("mixed-tenses", "I ___ Leo yesterday, but I ___ from him since then.", ["have seen / didn’t hear", "saw / haven’t heard", "was seeing / don’t hear", "had seen / am not hearing"], 1, "Yesterday requires past simple; since then connects the negative period to now."),
      c("mixed-tenses", "When the doors opened, hundreds of people ___ outside.", ["wait", "are waiting", "were waiting", "have waited"], 2, "The waiting was already in progress at that past moment."),
      c("mixed-tenses", "The documents ___ before the auditor asked for them.", ["destroyed", "were destroying", "had been destroyed", "have been destroyed tomorrow"], 2, "Earlier passive completion needs past perfect passive."),
      t("mixed-tenses", "Complete: ‘I ___ this book for two weeks, but I haven’t finished it.’ (read)", ["have been reading", "i have been reading", "i've been reading", "ive been reading"], "Duration plus unfinished activity favours present perfect continuous."),
      t("mixed-tenses", "Complete: ‘She ___ the email an hour ago.’ (send)", ["sent", "she sent"], "Ago marks finished past time and requires past simple."),
      t("mixed-tenses", "Correct: ‘The bridge is repairing at the moment.’", ["the bridge is being repaired at the moment", "the bridge is being repaired"], "The bridge receives the current action, so use present continuous passive."),
      r("mixed-tenses", "A busy morning", "I have been preparing for today’s presentation since six. When I reached the office, I discovered that the main screen had been damaged overnight. A replacement is being installed now.", "Which form describes duration connected to now?", ["reached", "had been damaged", "have been preparing", "is being installed"], 2, "Have been preparing connects the activity and its duration to the present."),
      r("mixed-tenses", "A busy morning", "I have been preparing for today’s presentation since six. When I reached the office, I discovered that the main screen had been damaged overnight. A replacement is being installed now.", "Why is ‘had been damaged’ used?", ["It is a current routine.", "It is a passive event before the past discovery.", "It is happening now.", "It expresses future evidence."], 1, "The damage occurred before the narrator discovered it, and the screen receives the action."),
      rt("mixed-tenses", "A busy morning", "I have been preparing for today’s presentation since six. When I reached the office, I discovered that the main screen had been damaged overnight. A replacement is being installed now.", "Complete the current passive process: ‘A replacement ___ now.’", ["is being installed"], "Now plus receiver focus requires present continuous passive."),
    ],
    "narrative-tenses": [
      c("narrative-tenses", "The wind ___ and the trees ___ as we approached the house.", ["blew / fell", "was blowing / were shaking", "had blown / have shaken", "has blown / shake"], 1, "Past continuous sets two simultaneous background conditions."),
      c("narrative-tenses", "Suddenly, a light ___ in the upstairs window.", ["appeared", "was appearing for hours", "had appeared after", "has appeared now"], 0, "Past simple introduces a completed event that advances the story."),
      c("narrative-tenses", "I recognised the man because I ___ his photograph earlier.", ["saw tomorrow", "was seeing now", "had seen", "have seen yesterday"], 2, "Seeing the photograph happened before the past recognition."),
      c("narrative-tenses", "Her clothes were wet because she ___ in the rain.", ["walked next week", "was walking after", "had walked once tomorrow", "had been walking"], 3, "Earlier ongoing activity explains the visible past result."),
      c("narrative-tenses", "While everyone ___, the door quietly opened.", ["talked once", "was talking", "had talked after", "has talked"], 1, "The talking is background interrupted by the door opening."),
      c("narrative-tenses", "He picked up the key, ___ it and put it in his pocket.", ["examined", "was examining when nothing happened", "had examined later", "has examined"], 0, "Past simple reports the main sequence."),
      c("narrative-tenses", "The room was empty. Someone ___ all the furniture.", ["removed after we entered", "was removing now", "had removed", "has been removing tomorrow"], 2, "The removal occurred before the characters saw the empty room."),
      c("narrative-tenses", "They ___ the building for days before they finally entered it.", ["watched tomorrow", "were watching after", "had watched one moment", "had been watching"], 3, "For days before a past event emphasises earlier duration."),
      t("narrative-tenses", "Complete the background: ‘It ___ heavily when the car stopped.’ (snow)", ["was snowing", "it was snowing"], "Past continuous sets the scene for the car stopping."),
      t("narrative-tenses", "Complete the flashback: ‘She knew the code because she ___ it before.’ (use)", ["had used", "she had used", "she'd used", "shed used"], "Past perfect marks experience before the past moment of knowing."),
      r("narrative-tenses", "The locked studio", "Rain was hitting the windows when Mara entered the studio. Someone had left a lamp on, although the owner had been travelling for a week. Mara heard a sound, turned around and saw a cat behind the curtain.", "Which verbs move the main story forward?", ["was hitting", "had left", "had been travelling", "heard, turned and saw"], 3, "The past-simple sequence reports the main events."),
      rt("narrative-tenses", "The locked studio", "Rain was hitting the windows when Mara entered the studio. Someone had left a lamp on, although the owner had been travelling for a week. Mara heard a sound, turned around and saw a cat behind the curtain.", "Complete the earlier duration: ‘The owner ___ for a week.’", ["had been travelling"], "The travelling continued during the week before the studio scene."),
    ],
    "time-expressions": [
      c("time-expressions", "I have lived here ___ 2020.", ["for", "since", "ago", "last"], 1, "Since introduces the starting point 2020."),
      c("time-expressions", "They have been waiting ___ two hours.", ["since", "for", "ago", "yesterday"], 1, "For introduces a duration."),
      c("time-expressions", "Have you finished the form ___?", ["already in every question", "yet", "ago", "last"], 1, "Yet commonly appears in present-perfect questions about an expected result."),
      c("time-expressions", "I’ve ___ spoken to Maya, so she knows the plan.", ["just", "ago", "last", "while"], 0, "Just marks a very recent event connected to now."),
      c("time-expressions", "We moved offices three months ___.", ["since", "for", "ago", "already"], 2, "Ago counts backwards from now and uses past simple."),
      c("time-expressions", "The company launched the product ___ year.", ["since", "last", "yet", "currently"], 1, "Last year is a finished past period."),
      c("time-expressions", "I’m working on the budget ___, so I can’t talk.", ["at the moment", "ago", "last week", "since 2018"], 0, "At the moment marks current activity."),
      c("time-expressions", "___ I was presenting, the fire alarm went off.", ["Already", "Since", "While", "Ago"], 2, "While introduces the longer action in progress."),
      t("time-expressions", "Complete with one marker: ‘She hasn’t replied ___.’", ["yet"], "Yet is natural in a negative present-perfect sentence."),
      t("time-expressions", "Complete: ‘___ the time we arrived, the shop had closed.’", ["by", "by the time"], "By the time introduces the later reference point."),
      r("time-expressions", "Project update", "We started the project six weeks ago and have already completed the research stage. We have been testing the prototype for ten days, but we haven’t received the final materials yet.", "Which marker introduces a duration?", ["ago", "already", "for", "yet"], 2, "For ten days gives the length of the testing activity."),
      rt("time-expressions", "Project update", "We started the project six weeks ago and have already completed the research stage. We have been testing the prototype for ten days, but we haven’t received the final materials yet.", "Complete the finished past marker: ‘We started six weeks ___.’", ["ago"], "Ago places the starting event in finished past time."),
    ],
    "choosing-tense": [
      c("choosing-tense", "She ___ five reports today; the fifth is on my desk.", ["writes", "is writing five", "has written", "has been writing five"], 2, "A completed quantity in unfinished today favours present perfect simple."),
      c("choosing-tense", "She ___ reports all day and needs a break.", ["writes every day", "is writing tomorrow", "has written a result", "has been writing"], 3, "All day plus need for a break emphasises ongoing activity."),
      c("choosing-tense", "I ___ him at the conference last Tuesday.", ["meet", "have met", "met", "have been meeting"], 2, "Last Tuesday is finished past time."),
      c("choosing-tense", "I ___ him several times this month.", ["met yesterday", "have met", "am meeting every month", "had met tomorrow"], 1, "This month is unfinished and several times gives present relevance."),
      c("choosing-tense", "At eight last night, we ___ the final scene.", ["filmed completely at nine", "were filming", "had filmed after eight", "have filmed"], 1, "The action was in progress at the specified past time."),
      c("choosing-tense", "When I called, they ___ the meeting.", ["already finished later", "were finishing yesterday after", "had already finished", "have already finished now"], 2, "The meeting finished before the past call."),
      c("choosing-tense", "The machine ___ every six months.", ["services technicians", "is serviced", "is being serviced every current second", "has servicing"], 1, "A regular process with receiver focus uses present simple passive."),
      c("choosing-tense", "Technicians ___ the machine right now.", ["service every day", "are servicing", "have serviced yesterday", "had serviced tomorrow"], 1, "Known agents and current activity call for present continuous active."),
      c("choosing-tense", "There is paint on his shirt. He ___ the wall.", ["paints routinely", "has painted a result only", "has been painting", "had painted before yesterday"], 2, "Visible evidence makes recent activity the focus."),
      c("choosing-tense", "The wall looks perfect. He ___ it.", ["has painted", "has been painting without result", "is paint", "painted tomorrow"], 0, "The completed visible result favours present perfect simple."),
      c("choosing-tense", "Which sentence focuses on the receiver and present result?", ["Someone has cancelled the flight.", "The flight has been cancelled.", "The flight is cancelling someone.", "Someone was cancel the flight."], 1, "Present perfect passive focuses on the cancelled flight."),
      c("choosing-tense", "Which form gives background rather than the main event?", ["The glass broke.", "People were dancing.", "The alarm rang.", "She opened the door."], 1, "Past continuous creates background in progress."),
      t("choosing-tense", "Complete for result: ‘I ___ the kitchen, so you can use it now.’ (clean)", ["have cleaned", "i have cleaned", "i've cleaned", "ive cleaned"], "The completed result matters now."),
      t("choosing-tense", "Complete for duration: ‘I ___ the kitchen for two hours.’ (clean)", ["have been cleaning", "i have been cleaning", "i've been cleaning", "ive been cleaning"], "For two hours emphasises the activity’s duration."),
      t("choosing-tense", "Change focus to the result: ‘Someone broke the window last night.’", ["the window was broken last night", "the window was broken last night."], "Past simple passive focuses on the window."),
      r("choosing-tense", "Choosing by context", "Lena works in finance, but this month she is helping the training team. She has prepared four workshops so far and has been answering questions since eight. Yesterday, the schedule was changed.", "Which contrast shows routine versus temporary activity?", ["has prepared / has been answering", "works / is helping", "was changed / works", "yesterday / since"], 1, "Present simple routine contrasts with present continuous temporary activity."),
      r("choosing-tense", "Choosing by context", "Lena works in finance, but this month she is helping the training team. She has prepared four workshops so far and has been answering questions since eight. Yesterday, the schedule was changed.", "Why is ‘was changed’ passive past simple?", ["The schedule acted yesterday.", "The change is current and ongoing.", "The receiver and finished past event are the focus.", "The agent must always be hidden."], 2, "Yesterday fixes past time, and the schedule receives the action."),
      rt("choosing-tense", "Choosing by context", "Lena works in finance, but this month she is helping the training team. She has prepared four workshops so far and has been answering questions since eight. Yesterday, the schedule was changed.", "Complete the duration focus: ‘She ___ questions since eight.’", ["has been answering", "she has been answering", "she's been answering", "shes been answering"], "Since eight and ongoing activity favour present perfect continuous."),
    ],
    "b2-cloze": [
      r("b2-cloze", "The unexpected exhibition", "When Priya arrived at the gallery, technicians were still installing the final lights. She had planned the exhibition for months, but nobody had told her that one painting had been damaged.", "When Priya arrived, technicians ___ the lights.", ["installed", "were installing", "had installed before all work", "have installed"], 1, "The installation was background in progress at arrival."),
      r("b2-cloze", "The unexpected exhibition", "When Priya arrived at the gallery, technicians were still installing the final lights. She had planned the exhibition for months, but nobody had told her that one painting had been damaged.", "She ___ the exhibition for months before that morning.", ["plans now", "was planning after arrival", "had been planning", "has planned tomorrow"], 2, "Earlier duration leading to the past arrival needs past perfect continuous."),
      r("b2-cloze", "The unexpected exhibition", "When Priya arrived at the gallery, technicians were still installing the final lights. She had planned the exhibition for months, but nobody had told her that one painting had been damaged.", "Why is ‘had been damaged’ passive?", ["The painting caused damage.", "The receiver and earlier result are the focus.", "All perfect forms are passive.", "The damage is happening now."], 1, "The painting received the earlier action before Priya arrived."),
      t("b2-cloze", "Complete the flashback: ‘Nobody ___ her about the damage.’ (tell)", ["had told", "nobody had told"], "The absence of telling belongs before the past arrival."),
      c("b2-cloze", "Choose the best sequence: ‘Priya ___ the manager and ___ for an explanation.’", ["called / asked", "was calling / had asked later", "has called / asks", "had called / was asking before arriving"], 0, "Past simple advances the main sequence with two completed actions."),
      t("b2-cloze", "Complete the background: ‘Visitors ___ outside while the team worked.’ (wait)", ["were waiting", "visitors were waiting"], "Past continuous supplies simultaneous background."),
      r("b2-cloze", "A research update", "Scientists have recently identified a new pattern in the data. They have been studying the samples since January, and more than two hundred tests have been completed. A second laboratory is currently checking the results.", "Scientists ___ the samples since January.", ["study every January", "are studying since", "have studied yesterday", "have been studying"], 3, "Since January and ongoing research favour present perfect continuous."),
      r("b2-cloze", "A research update", "Scientists have recently identified a new pattern in the data. They have been studying the samples since January, and more than two hundred tests have been completed. A second laboratory is currently checking the results.", "Why is ‘have been completed’ used?", ["The tests perform the action.", "The completed quantity and receiver are central.", "It describes a past background.", "Currently always requires perfect."], 1, "Present perfect passive focuses on the completed test total."),
      r("b2-cloze", "A research update", "Scientists have recently identified a new pattern in the data. They have been studying the samples since January, and more than two hundred tests have been completed. A second laboratory is currently checking the results.", "Which form describes activity happening around now?", ["have identified", "have been completed", "is currently checking", "since January"], 2, "Present continuous with currently describes the present activity."),
      t("b2-cloze", "Complete the recent result: ‘Scientists ___ a new pattern.’ (identify)", ["have identified", "scientists have identified"], "Recently and present relevance support present perfect."),
      c("b2-cloze", "Choose the best marker: ‘The second team hasn’t confirmed the results ___.’", ["ago", "last", "yet", "while"], 2, "Yet fits an expected result in a negative present-perfect sentence."),
      t("b2-cloze", "Complete the current passive process: ‘The results ___ by a second laboratory.’ (check)", ["are being checked", "the results are being checked"], "A process happening now with receiver focus needs present continuous passive."),
      r("b2-cloze", "The overnight journey", "We had been driving for four hours when the engine suddenly stopped. While Sam was calling for help, I checked the map. The road had been closed earlier, but no warning signs had been placed at the junction.", "We ___ for four hours when the engine stopped.", ["drove later", "were driving after", "had driven one completed trip", "had been driving"], 3, "Duration before the stopping point needs past perfect continuous."),
      r("b2-cloze", "The overnight journey", "We had been driving for four hours when the engine suddenly stopped. While Sam was calling for help, I checked the map. The road had been closed earlier, but no warning signs had been placed at the junction.", "What was Sam doing while the narrator checked the map?", ["He called after everything ended.", "He was calling for help.", "He had called before driving.", "He has called now."], 1, "Past continuous describes the simultaneous action in progress."),
      r("b2-cloze", "The overnight journey", "We had been driving for four hours when the engine suddenly stopped. While Sam was calling for help, I checked the map. The road had been closed earlier, but no warning signs had been placed at the junction.", "Why is ‘had been placed’ passive past perfect?", ["The signs placed the workers.", "It is a current process.", "It describes an earlier missing action with signs as receiver.", "All road sentences are passive."], 2, "Placement should have occurred before the past journey; the signs receive the action."),
      t("b2-cloze", "Complete the main event: ‘The engine suddenly ___.’ (stop)", ["stopped", "the engine stopped"], "Past simple advances the story with a completed event."),
      c("b2-cloze", "Choose the best connector: ‘___ Sam was calling, I checked the map.’", ["Already", "While", "Ago", "Yet"], 1, "While links simultaneous actions and introduces the longer one."),
      t("b2-cloze", "Complete the earlier passive: ‘The road ___ earlier.’ (close)", ["had been closed", "the road had been closed"], "The closing happened before the past engine problem and the road receives the action."),
    ]
  };

  const exercises = [];
  Object.entries(banks).forEach(([topic, items]) => items.forEach((item, index) => exercises.push({
    ...item,
    id: `${topic}-${String(index + 1).padStart(2, "0")}`,
    partial: 1,
    quickTest: index < 8,
    exam: [0, 2, 5, 8, 10].includes(index) ? 1 : null
  })));

  window.Partial1Data = { topics, guides, exercises };
})();
