(() => {
  "use strict";

  const university = window.EnglishUniversityData;
  const catalogs = window.EnglishCatalogs;
  if (!university || !catalogs) return;

  const models = {
    "Explain a change of plan": {
      text: `Hi Olivia,\n\nI am sorry, but I cannot meet you at the sports centre on Saturday morning because my work schedule has changed. A colleague is ill, so I have agreed to cover her shift until two o'clock.\n\nCould we go on Sunday afternoon instead? The centre is open until six, and I can book the badminton court for four o'clock. If Sunday is not convenient, we could meet for coffee after my shift on Saturday.\n\nWhich option works better for you?\n\nSee you soon,\nJamie`,
      commentary: "The message explains the reason immediately, offers two realistic alternatives and closes with a clear question in an informal register."
    },
    "Describe a useful object": {
      text: `The most useful object on my desk is a small adjustable lamp that my sister gave me last year. It has a round base, a flexible metal arm and three levels of brightness. Because the arm moves easily, I can direct the light towards a book or away from my computer screen.\n\nI use the lamp almost every evening when I study. The brightest setting helps me read small diagrams, while the softer light is comfortable when I only need to review notes. It is valuable to me not because it is expensive, but because it makes my study space calmer and reminds me of my sister whenever I switch it on.`,
      commentary: "The description moves from identification to physical detail, function and personal value, using relative and reason clauses naturally."
    },
    "Invite a friend to a local event": {
      text: `Hi Noah,\n\nAre you free next Saturday? Our neighbourhood is holding an outdoor film night in Riverside Park, and I would love you to come with me. The film starts at eight, but we are meeting near the main gate at seven so that we can find a good place and buy something to eat.\n\nYou would enjoy it because the organisers are showing a science-fiction film, and a local band is playing before it begins. I am bringing a blanket, but you might want to bring a jacket because it gets cool after sunset.\n\nWould you like to join us?\n\nTake care,\nEmma`,
      commentary: "The email gives complete practical details, makes the invitation appealing and uses present continuous naturally for a confirmed arrangement."
    },
    "A problem that taught me something": {
      text: `Last autumn, I was travelling to an important interview when my phone suddenly stopped working. I had saved the address only in an app, so I could not check the final part of the route. At first, I panicked and walked in the wrong direction.\n\nThen I stopped at a café and asked a member of staff for help. She drew a simple map and showed me a bus that stopped near the office. I arrived five minutes before the interview began.\n\nThe experience taught me not to depend on one device for essential information. I now write important addresses in a notebook and leave extra travel time. The problem was stressful, but it changed a careless habit into a useful routine.`,
      commentary: "The narrative establishes the situation, develops the problem and response, and ends with a specific lesson rather than a general slogan."
    },
    "The best way to learn a practical skill": {
      text: `In my view, the best way to learn a practical skill is to combine a clear demonstration with immediate practice. Watching an expert can show the correct sequence, but observation alone does not reveal which parts will be difficult for you.\n\nFor example, I learned to repair a bicycle tyre by first watching a short demonstration. I then repeated each step while an experienced friend checked my work. Although I made several mistakes, the feedback helped me understand why the tyre was still losing air.\n\nI would therefore recommend a simple cycle: watch, try, receive feedback and try again. Instructions are useful, but a practical skill becomes reliable only when you can perform it independently and correct your own errors.`,
      commentary: "The response states a position, develops it with a relevant personal example and ends with a practical, memorable recommendation."
    },
    "Should public spaces offer free Wi-Fi?": {
      text: `Free Wi-Fi in libraries, transport hubs and public squares can improve access to information, particularly for people who cannot afford reliable mobile data. It may also help visitors use maps, contact services and complete urgent tasks. For these reasons, public access can support both inclusion and local economic activity.\n\nNevertheless, a free network is not automatically a public benefit. Installation and maintenance cost money, and an insecure service may expose users to avoidable risks. There is also a danger that authorities will treat internet access as a substitute for staffed services or suitable study spaces.\n\nOn balance, major public spaces should offer free Wi-Fi, provided that the service includes clear security guidance, reasonable data protection and continued investment in non-digital access. The aim should be to give residents another useful option, not to force every interaction online. A limited service with transparent safeguards is more defensible than either unrestricted access or no public connection at all.`,
      commentary: "The essay develops both sides, narrows the recommendation through conditions and keeps the conclusion connected to inclusion rather than technology alone."
    },
    "Review a course or service": {
      text: `I recently completed a six-week online course called Practical Data Stories. It is designed for learners who understand basic charts but want to explain evidence more clearly to a general audience.\n\nThe strongest feature is the weekly project. Instead of answering only multiple-choice questions, students rewrite a confusing chart title, record a short explanation and respond to another learner's work. The instructor's examples are concise and the feedback normally identifies one change that can be applied immediately.\n\nThe main limitation is the discussion platform, which is difficult to search. Useful answers often disappear inside long threads, and the mobile version makes comparison awkward. A short index of common questions would improve the experience considerably.\n\nDespite this weakness, I would recommend the course to students and professionals who need to present evidence. It is practical, demanding without being overwhelming and especially valuable for anyone who tends to describe every number instead of explaining the main pattern.`,
      commentary: "The review identifies audience, evaluates concrete strengths and limitations and gives a qualified recommendation based on likely reader needs."
    },
    "Improve a shared workspace": {
      text: `Report: Improving the Shared Workspace\n\nFindings\nThe workspace is used regularly, but observation and user comments identified two recurring problems. Video meetings create noise for people completing focused work, while the two small meeting rooms are often occupied by one person. In addition, equipment faults are reported informally and are not always resolved.\n\nRecommendations\nA quiet zone should be established along the east wall, where calls would not be permitted. Two sound-controlled call booths could be installed near the entrance so that short online meetings do not require a full room. The booking system should also ask users to choose an appropriate space according to group size.\n\nFinally, a simple digital fault log is recommended. Each report should include the equipment, location, problem and current status. A facilities owner could review the list daily and publish an expected completion date.\n\nConclusion\nThese measures would improve concentration and make better use of limited space. Their impact should be reviewed after six weeks through occupancy data and a short user survey.`,
      commentary: "The report separates evidence from recommendations, uses headings and passive structures appropriately, and defines a review method."
    },
    "Living without a private car": {
      text: `Living without a private car can reduce household costs and encourage people to walk, cycle or use public transport. In dense cities, this choice may also save time because drivers do not need to find parking or maintain a vehicle that remains unused for much of the day. A wider reduction in car use can improve air quality and make streets safer.\n\nOn the other hand, the decision is not equally practical for everyone. Public transport may be unreliable in rural areas, and families with mobility needs or irregular working hours can have few realistic alternatives. Car-sharing services can help, but their price and availability vary.\n\nThe advantages are therefore strongest where communities provide frequent transport, safe walking routes and access to occasional shared vehicles. Living without a car should be made possible rather than treated as a moral requirement. For some residents it offers greater freedom; for others, the absence of transport alternatives would create a serious barrier to work, care and social participation.`,
      commentary: "The essay develops genuine benefits and constraints, then concludes by identifying the conditions under which the advantages are most credible."
    },
    "Request action after a service failure": {
      text: `Subject: Request for replacement following repeated device failure\n\nDear Customer Support Team,\n\nI am writing regarding order 48172, a wireless router purchased on 4 March. The device has stopped connecting to the internet three times during the past two weeks. On each occasion, I followed the reset procedure provided by your support team, but the fault returned within a day.\n\nThe repeated loss of service has prevented me from attending two scheduled online meetings. Although I appreciate the assistance already provided, another temporary reset is unlikely to resolve the underlying problem.\n\nI would therefore like to request a replacement device under the warranty. Please confirm whether the faulty router should be returned by post or taken to a local branch. I can provide the original receipt, serial number and copies of the support conversations if required.\n\nI would be grateful for a response within five working days.\n\nYours faithfully,\nMorgan Lee`,
      commentary: "The email remains factual and polite, documents previous attempts and requests a specific action with the information needed to complete it."
    },
    "Create a student mentoring programme": {
      text: `Proposal: Peer Mentoring Programme\n\nPurpose\nThis proposal outlines a voluntary programme that would connect first-year students with trained second-year mentors during their first semester.\n\nDesign\nMentors would meet a small group twice a month to discuss study planning, university services and common transition problems. A short training session would cover listening, boundaries and referral to professional support. Mentors would not provide academic answers or counselling.\n\nBenefits\nThe programme could give new students a reliable contact before small difficulties become serious. Mentors would also develop facilitation and communication skills. Group meetings would enable the college to support more students without replacing existing advisers.\n\nImplementation\nA twelve-week pilot with forty first-year students is recommended. Recruitment should begin before the semester, and each meeting should use a simple discussion guide. Success could be measured through attendance, participant feedback and the proportion of students who report knowing where to seek specialist help.\n\nRecommendation\nThe pilot should proceed provided that one staff member is assigned to training, safeguarding and referral questions.`,
      commentary: "The proposal defines scope, protects role boundaries and connects expected benefits to measurable evidence."
    },
    "One habit that changed how I learn": {
      text: `What happens to a useful idea a week after you first read it? In my case, it used to disappear beneath pages of highlighted notes. I felt productive while studying, but I rarely checked whether I could retrieve anything later.\n\nThat changed when I began ending each session with a blank page. I close the book and write the main idea, one example and one question from memory. The first attempts were uncomfortable because the gaps were obvious. However, those gaps told me exactly what to review.\n\nThe habit takes only five minutes, yet it has changed my relationship with mistakes. Forgetting is no longer proof that a session failed; it is information about what needs another encounter. My notes are now shorter, and I can explain more without looking at them.\n\nTry the blank-page test after your next study session. Do not aim for a perfect summary. Aim to discover what your memory can already rebuild—and what it cannot yet.`,
      commentary: "The article opens with a direct question, develops a personal turning point and ends by inviting the reader to try a specific action."
    },
    "The message arrived just in time": {
      text: `Rain was striking the station windows when Eva looked at the departure board for the fifth time. Her last train home was due in twelve minutes, but Daniel had not arrived. He had promised to bring the folder containing their scholarship application, which had to be submitted before midnight.\n\nEva was calling him again when the lights above platform six changed. Boarding had begun. She considered leaving without the folder, but then a message appeared: “Locker 18. Code 9041. I am stuck across town.”\n\nDragging her suitcase behind her, Eva ran towards the lockers. She had just entered the code when the station announcement warned that the doors would close in two minutes. Inside was the folder and a note explaining that Daniel had been helping a cyclist after an accident.\n\nEva reached the train as the doors began to move. Hours later, she submitted the application with forty seconds remaining. The delay had almost destroyed their plan, yet Daniel's final message—and his decision to help a stranger—made the success feel more valuable.`,
      commentary: "The narrative controls background, earlier events and a timed turning point, then closes with a consequence that changes the meaning of the delay."
    },
    "Reduce unnecessary meetings": {
      text: `Proposal: Reducing Unnecessary Meetings\n\nPurpose\nThe organisation should reduce meetings that distribute information without requiring discussion, while protecting sessions that produce decisions or resolve uncertainty.\n\nOptions\nRoutine updates could be replaced by a short written format containing progress, risk, next action and owner. Meetings would remain appropriate when participants must compare options, negotiate priorities or interpret incomplete evidence. A twenty-five-minute default would encourage focused agendas without preventing longer sessions where complexity justifies them.\n\nRecommendation\nA six-week pilot is proposed for three teams. Every invitation should state the decision required and link to essential preparation. Participants should be able to decline when their contribution is not needed, provided that they read the final record.\n\nImplementation and review\nMeeting hours, decision completion and participant feedback should be measured together. A reduction in hours would not count as success if unresolved work simply moved into private messages. The pilot should be revised if teams report delayed decisions or reduced access to colleagues.\n\nThis approach would treat a meeting as a tool with a defined purpose rather than a sign that collaboration has occurred.`,
      commentary: "The proposal avoids a simplistic anti-meeting position, defines when meetings are valuable and includes counter-metrics to detect displaced work."
    },
    "A decision made too late": {
      text: `By the time the storm warning became severe, the research team had already spent six hours preparing to cross the valley. The equipment was packed, the route had been checked and everyone wanted to avoid losing another day. Looking at the pale sky above the camp, Mara decided that the weather report was probably too cautious.\n\nThey had been walking for less than an hour when the wind began to push dust across the path. The guide suggested turning back, but Mara asked the group to continue until the next ridge. Reaching it twenty minutes later, they saw rain moving rapidly across the valley.\n\nThe return journey took twice as long. A flooded stream forced them to leave part of the equipment in a shelter, and one researcher injured his ankle on the wet ground. No one was seriously hurt, but the team lost three days recovering the instruments.\n\nDuring the review, Mara realised that she had treated preparation as evidence that the plan should continue. The difficult decision had not been to cancel the trip; it had been to accept that earlier effort could not make a worsening situation safe.`,
      commentary: "The model uses narrative tenses and participle clauses to manage chronology, then reflects on the decision-making error instead of ending with action alone."
    },
    "Does convenience improve life?": {
      text: `Convenience is commonly treated as an uncomplicated benefit: a process requires fewer steps, a service arrives more quickly or a device removes a routine decision. In many contexts this judgement is justified. Accessible design and reduced administrative effort can return time and independence to people who previously faced unnecessary barriers.\n\nThe concept becomes less convincing when the removed effort also performed a useful function. A pause before publishing may allow verification; a conversation with a local employee may reveal needs that a standard form cannot anticipate. Moreover, convenience for one participant may transfer work or risk to another. Instant delivery feels effortless to the customer partly because time pressure is absorbed elsewhere in the system.\n\nDefenders of friction sometimes romanticise difficulty. A confusing interface does not become valuable merely because it forces attention, and administrative delay rarely produces wisdom. The relevant distinction is therefore not between convenience and effort, but between needless effort and useful deliberation.\n\nConvenience improves life when it removes barriers without concealing consequences or weakening judgement. Evaluating it requires more than measuring speed. We must ask whose effort disappeared, whose effort increased and which opportunities for reflection or human response were lost.`,
      commentary: "The response defines a distinction, tests both extremes and reaches a nuanced criterion that can be applied beyond the examples."
    },
    "Respond to a disputed decision": {
      text: `Dear Review Committee,\n\nI am writing to request reconsideration of the decision not to fund the Community Data Project. I recognise the committee's concern that the initial proposal did not provide sufficient detail about long-term maintenance. This is a legitimate issue, and the revised plan now assigns responsibility for data storage and annual review to the university library.\n\nThe decision letter also states that the project duplicates an existing public dashboard. This conclusion appears to overlook a central distinction. The existing dashboard publishes regional totals, whereas the proposed project would document neighbourhood-level access barriers through interviews and service records. Its purpose is not to reproduce the same figures but to explain patterns that the aggregate data cannot reveal.\n\nI have attached the revised maintenance plan and a comparison of the two projects' scope, sources and intended users. I would be grateful if the committee could review the application in light of this additional evidence or clarify which remaining criterion has not been met.\n\nYours sincerely,\nDr Riley Chen`,
      commentary: "The letter acknowledges a valid concern, challenges a separate point with evidence and requests a proportionate next action without becoming hostile."
    },
    "Combine two viewpoints": {
      text: `Debates about recorded university lectures often present access and participation as opposing goals. Advocates argue that recordings allow students to revisit complex explanations and support those whose work, health or caring responsibilities interrupt attendance. Critics respond that routine recording can reduce live participation and may encourage students to postpone engagement.\n\nThe two positions share an assumption that recordings influence behaviour, but they differ in the behaviour they prioritise. Access-based arguments treat flexible review as a condition for participation; engagement-based arguments emphasise the value of responding during the event itself. Evidence from attendance alone cannot resolve the disagreement, because a lower physical attendance rate may represent disengagement or a different pattern of study.\n\nA more useful evaluation would distinguish lecture purpose and student action. Recordings are likely to support learning where students need to revisit dense explanation, particularly when they are paired with prompts that require active retrieval. They may offer less value in seminars whose purpose is interaction and immediate feedback.\n\nThe strongest policy is therefore selective rather than universal. Core explanations could be recorded with clear expectations for follow-up work, while interactive sessions would require a different form of access support. This synthesis preserves the legitimate concern about participation without treating physical presence as the only evidence of engagement.`,
      commentary: "The model organises sources by the question they answer, separates shared assumptions from disagreement and develops a policy from the synthesis."
    },
    "Should high-impact algorithms require public audits?": {
      text: `Algorithms used in hiring, credit, education or public benefits can influence opportunities at a scale that individual decisions rarely achieve. Public audits are therefore attractive: they promise evidence about accuracy, unequal outcomes and whether safeguards operate as claimed. For high-impact systems, some form of independent scrutiny should be required.\n\nThe strongest case for an audit is not that every automated decision is uniquely dangerous. Human institutions also produce opaque and biased outcomes. Rather, systematic tools create repeatable processes that can be tested across groups and over time. An independent audit can identify patterns that a single affected person cannot observe.\n\nA compelling objection concerns security, privacy and commercial information. Full publication of code or personal data could create genuine harm and still fail to explain how a system behaves in practice. This objection weakens the case for unrestricted disclosure, not for accountability itself. Auditors can inspect protected material while publishing methods, aggregate outcomes, limitations and corrective actions.\n\nPublic audits should therefore be mandatory where a system materially affects rights or access to essential opportunities. The requirement must be proportional and should evaluate outcomes, data, appeal routes and governance rather than treating source-code publication as a complete solution. Transparency is valuable only when it enables informed challenge and change.`,
      commentary: "The argument defines scope, answers a serious objection and distinguishes meaningful accountability from indiscriminate disclosure."
    },
    "Is efficiency always a social benefit?": {
      text: `Efficiency describes a relationship between resources and output, but it does not determine which output deserves priority. From one perspective, more efficient systems can lower cost, reduce waste and make scarce services available to more people. A faster diagnostic process or a simpler benefits application may remove delays that cause real harm.\n\nA second perspective asks where the saved effort goes. Efficiency for a customer may depend on additional pressure for a worker, just as rapid delivery may shift environmental cost outside the price. It can also reduce resilience: a tightly optimised system with no spare capacity performs well under normal conditions but fails dramatically when demand changes.\n\nCriticism of efficiency can nevertheless become vague. Wasteful administration does not protect human values merely because it is slow, and spare capacity requires resources that could be used elsewhere. A more defensible distinction separates efficiency within a chosen purpose from the prior decision about purpose, distribution and acceptable risk.\n\nEfficiency is therefore a conditional social benefit. It is valuable when the outcome itself is worthwhile, the saved resources are not produced through hidden harm and the system retains enough capacity to respond to uncertainty. Without those conditions, an impressive efficiency measure may simply describe how effectively an organisation pursues the wrong objective.`,
      commentary: "The essay examines competing perspectives, challenges simplistic versions of both and synthesises them through explicit conditions."
    },
    "Evaluate an international research partnership": {
      text: `Report: Evaluation of the Coastal Research Partnership\n\nPurpose\nThis report evaluates the first year of the partnership between Northshore University and the Bay Institute, with particular attention to research output, data governance and staff development.\n\nFindings\nThe teams completed two joint field studies and created a shared sampling protocol, reducing inconsistent measurements across sites. Early-career researchers valued access to specialist equipment and cross-institution mentoring. A recurring concern, however, was that data-cleaning work fell disproportionately to the Bay Institute, while publication decisions were led mainly by Northshore staff.\n\nRisks\nThe current agreement defines institutional ownership but does not specify authorship criteria, workload review or how community partners can approve sensitive interpretation. If these issues remain unresolved, trust and future data access may be weakened.\n\nRecommendations\nA quarterly workload review should record technical, analytical and coordination contributions. Authorship criteria ought to be agreed before each study begins, and a community review stage should be added before publication of locally sensitive findings. A rotating chair would distribute agenda-setting authority more evenly.\n\nConclusion\nThe partnership has produced valuable scientific and professional outcomes, but its sustainability depends on making invisible work and decision rights explicit.`,
      commentary: "The report balances achievement with governance risk and proposes mechanisms that directly address the evidence found."
    },
    "Create an ethical technology review panel": {
      text: `Proposal: Ethical Technology Review Panel\n\nRationale\nThe organisation currently evaluates technical performance and legal compliance separately. A cross-functional panel would identify social, operational and rights-related risks before high-impact tools are deployed.\n\nMembership\nThe panel should include engineering, security, legal, user research and operational staff, together with an independent member able to represent affected users. Membership should rotate, while specialist advisers could be invited where a project raises domain-specific questions.\n\nProcess\nTeams would submit a concise impact record covering purpose, data, likely benefits, foreseeable harm, affected groups, safeguards and appeal routes. The panel would be mandated to approve a limited pilot, request revision or pause deployment. Decisions and dissenting views should be recorded.\n\nAccountability\nApproval would be subject to review after real outcome data becomes available. A public summary should describe the system's purpose, principal risks, safeguards and review date without exposing personal or security-sensitive information.\n\nRecommendation\nThe panel should begin with a six-month pilot focused on recruitment and customer eligibility tools. Its own effectiveness should be evaluated through the quality of revisions, unresolved incidents and feedback from teams and affected users.`,
      commentary: "The proposal gives the panel real authority, defines inputs and outputs, and includes transparency and review of the governance process itself."
    },
    "Explain why correlation is not sufficient for causation": {
      text: `Correlation describes a relationship in which two measured variables change together. Such a pattern can be informative, but it is not sufficient to establish that one variable causes the other. Several alternative explanations remain possible.\n\nFirst, the direction may be reversed. A study might find that people who sleep less report more stress, yet stress could also reduce sleep. Second, a third factor may influence both variables. Irregular working hours, for example, could affect sleep and stress simultaneously. Selection can create another distortion if the people included in a study differ systematically from those who are absent.\n\nA causal claim therefore requires more than statistical association. Researchers need a plausible mechanism and a design that reduces alternative explanations. Random assignment can balance many confounding factors, although it is not always ethical or practical. Longitudinal evidence, natural experiments and careful statistical controls can strengthen an inference, but each depends on assumptions that should be stated.\n\nThe distinction matters because policy acts on causes, not merely predictors. A correlated variable may still be useful for forecasting, but changing it will improve the outcome only if the causal relationship is genuine or if the intervention affects the relevant mechanism. Responsible interpretation separates what the data predicts from what it demonstrates about intervention.`,
      commentary: "The explanation defines the concept, develops multiple alternatives, describes methodological responses and connects the distinction to real decisions."
    }
  };

  catalogs.writingCatalog.forEach((brief) => {
    const model = models[brief.title];
    if (model) {
      brief.modelAnswer = model.text;
      brief.modelCommentary = model.commentary;
      brief.usefulGrammar = brief.language;
      brief.selfReviewCriteria = ["Grammar", "Vocabulary", "Coherence", "Cohesion", "Organisation", "Register", "Accuracy", "Range"];
    }
  });

  university.activities.filter((item) => item.skill === "writing" && item.mode === "challenge").forEach((item) => {
    const brief = catalogs.writingCatalog.find((candidate) => `${item.title || ""} ${item.prompt || ""}`.includes(candidate.title));
    if (!brief?.modelAnswer) return;
    item.wordLimit ||= brief.wordLimit;
    item.recommendedStructure ||= brief.structure;
    item.usefulLanguage ||= brief.language;
    item.usefulGrammar ||= brief.usefulGrammar;
    item.selfReviewCriteria = brief.selfReviewCriteria;
    item.modelAnswer = brief.modelAnswer;
    item.modelCommentary = brief.modelCommentary;
  });

  const customModels = {
    "writing-b1-email": models["Explain a change of plan"],
    "writing-b2-report": models["Improve a shared workspace"],
    "writing-c1-synthesis": models["Combine two viewpoints"],
    "writing-b1-description": {
      text: `The place that matters most to me is a narrow balcony outside my family's apartment. It is only large enough for two chairs and several plant pots, but in the early morning it feels separate from the busy street below. I can hear buses in the distance and smell the herbs that my father grows beside the wall.\n\nI often sit there before work with a cup of coffee. The balcony is where I read, plan difficult days and talk quietly with my sister. It matters to me because it has been part of many ordinary family moments. Nothing dramatic has happened there, yet the familiar light, sounds and plants make it the place where I feel most settled.`,
      commentary: "The description combines location, sensory detail, routine and personal significance instead of presenting an isolated adjective list."
    },
    "writing-b2-opinion": {
      text: `Schools should teach practical financial skills because young people make real decisions about spending, contracts and debt before many of them receive reliable guidance. A compulsory course could explain budgeting, interest, taxes and the risks of common forms of borrowing. This knowledge would not guarantee perfect choices, but it would give students a clearer basis for evaluating them.\n\nCritics may argue that families should provide financial education or that the curriculum is already crowded. Family experience is valuable, yet access to accurate information is unequal. Moreover, financial topics can be integrated with mathematics, citizenship and digital safety rather than taught as an entirely separate subject.\n\nThe course would need to remain practical and independent of commercial influence. Students should compare real contract terms, identify misleading claims and explain the consequences of different choices. In my view, financial education should therefore be compulsory, provided that it develops judgement rather than promoting one lifestyle. Its aim should be to help students ask informed questions before a decision becomes expensive or difficult to reverse.`,
      commentary: "The essay develops a clear case, addresses curriculum and family objections, and qualifies the recommendation through practical conditions."
    }
  };

  Object.entries(customModels).forEach(([id, model]) => {
    const item = university.activities.find((candidate) => candidate.id === id);
    if (!item || !model) return;
    item.modelAnswer = model.text;
    item.modelCommentary = model.commentary;
    item.selfReviewCriteria = ["Grammar", "Vocabulary", "Coherence", "Cohesion", "Organisation", "Register", "Accuracy", "Range"];
  });
})();
